import type { Plugin } from "@elizaos/core";
export declare const shellPlugin: Plugin;
export default shellPlugin;
export { shellHistoryProvider } from "./providers/shellHistoryProvider";
export {
  addSession,
  appendOutput,
  clearFinished,
  createSessionSlug,
  deleteSession,
  drainSession,
  getFinishedSession,
  getSession,
  listFinishedSessions,
  listRunningSessions,
  markBackgrounded,
  markExited,
  resetProcessRegistryForTests,
  setJobTtlMs,
  tail,
  trimWithCap,
} from "./services/processRegistry";
export { ShellService } from "./services/shellService";
export type {
  CommandHistoryEntry,
  CommandResult,
  ExecResult,
  ExecuteOptions,
  FileOperation,
  FileOperationType,
  FinishedSession,
  ProcessAction,
  ProcessActionParams,
  ProcessSession,
  ProcessStatus,
  PtyExitEvent,
  PtyHandle,
  PtyListener,
  PtySpawn,
  SessionStdin,
  ShellConfig,
} from "./types";
export {
  DEFAULT_FORBIDDEN_COMMANDS,
  extractBaseCommand,
  isForbiddenCommand,
  isSafeCommand,
  loadShellConfig,
  validatePath,
} from "./utils";
export {
  BRACKETED_PASTE_END,
  BRACKETED_PASTE_START,
  buildCursorPositionResponse,
  encodeKeySequence,
  encodePaste,
  type KeyEncodingRequest,
  type KeyEncodingResult,
  stripDsrRequests,
} from "./utils/ptyKeys";
export {
  chunkString,
  clampNumber,
  coerceEnv,
  deriveSessionName,
  formatDuration,
  formatSpawnError,
  getShellConfig,
  killProcessTree,
  killSession,
  pad,
  readEnvInt,
  resolveWorkdir,
  type SpawnFallback,
  type SpawnWithFallbackResult,
  sanitizeBinaryOutput,
  sliceLogLines,
  sliceUtf16Safe,
  spawnWithFallback,
  truncateMiddle,
} from "./utils/shellUtils";
