#!/usr/bin/env python3
"""
Build OPNPHN01 test images for the verifier KAT harness.

The container layout is taken byte-for-byte from
docs/security/boot-image-format.md §2.1 / §2.2:

  header(256) || payload(image_size) || sig_blob(96)

Signing uses an independent Ed25519 implementation (python `cryptography`) so
the harness cross-checks the C verifier against a different codebase. Keys are
derived from fixed seeds so the output is fully deterministic.

Emits, into the output directory:
  good.bin            valid, accepted
  bad_payload.bin     one payload byte flipped after signing (payload-hash + sig fail)
  wrong_key.bin       signed by a key whose hash != expected root
  bad_rollback.bin    rollback_index below the OTP floor
  bad_magic.bin       corrupted magic
  revoked.bin         valid signature but key_id is in the revoked bitmap
  expected.h          C header with the OTP root key hash and per-image params
"""

import hashlib
import struct
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

HEADER_LEN = 256
SIG_LEN = 96
MAGIC = b"OPNPHN01"

# Lifecycle one-hot (boot-image-format.md §5).
LC_LOCKED = 0x08

# OTP state the C test feeds the verifier for the positive case.
OTP_ROLLBACK_MIN = 4
OTP_REVOKED_BITMAP = 0x00
OTP_LIFECYCLE = LC_LOCKED


def key_from_seed(seed: int) -> Ed25519PrivateKey:
    raw = hashlib.sha256(f"opnphn01-test-key-{seed}".encode()).digest()
    return Ed25519PrivateKey.from_private_bytes(raw)


def pub_raw(key: Ed25519PrivateKey) -> bytes:
    return key.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)


def build_header(
    image_type: int,
    payload: bytes,
    rollback_index: int,
    rollback_slot: int,
    key_id: int,
    flags: int,
    next_stage_pubkey_hash: bytes,
    min_lifecycle_state: int,
) -> bytes:
    payload_sha = hashlib.sha256(payload).digest()
    h = bytearray(HEADER_LEN)
    h[0x00:0x08] = MAGIC
    struct.pack_into("<I", h, 0x08, 1)  # header_version
    struct.pack_into("<I", h, 0x0C, image_type)
    struct.pack_into("<Q", h, 0x10, len(payload))
    struct.pack_into("<I", h, 0x18, rollback_index)
    struct.pack_into("<I", h, 0x1C, rollback_slot)
    struct.pack_into("<I", h, 0x20, key_id)
    struct.pack_into("<I", h, 0x24, flags)
    h[0x28:0x48] = payload_sha
    h[0x48:0x68] = next_stage_pubkey_hash
    struct.pack_into("<I", h, 0x68, min_lifecycle_state)
    # 0x6C..0x100 reserved, zero-filled, covered by the signature.
    return bytes(h)


def build_image(
    signing_key: Ed25519PrivateKey,
    image_type: int = 0,
    payload: bytes = b"E1 BL1 first-stage payload bytes for the KAT harness.",
    rollback_index: int = 7,
    rollback_slot: int = 0,
    key_id: int = 1,
    flags: int = 0,
    next_stage_pubkey_hash: bytes = b"\x00" * 32,
    min_lifecycle_state: int = LC_LOCKED,
) -> bytes:
    header = build_header(
        image_type,
        payload,
        rollback_index,
        rollback_slot,
        key_id,
        flags,
        next_stage_pubkey_hash,
        min_lifecycle_state,
    )
    signed = header + payload
    signature = signing_key.sign(signed)
    sig_blob = pub_raw(signing_key) + signature
    assert len(sig_blob) == SIG_LEN
    return header + payload + sig_blob


def main() -> int:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent
    out.mkdir(parents=True, exist_ok=True)

    root_key = key_from_seed(1)
    attacker_key = key_from_seed(99)
    root_hash = hashlib.sha256(pub_raw(root_key)).digest()

    good = build_image(root_key)
    (out / "good.bin").write_bytes(good)

    bad_payload = bytearray(good)
    # Flip a byte inside the payload region (after the 256-byte header).
    bad_payload[HEADER_LEN + 4] ^= 0x01
    (out / "bad_payload.bin").write_bytes(bytes(bad_payload))

    (out / "wrong_key.bin").write_bytes(build_image(attacker_key))

    (out / "bad_rollback.bin").write_bytes(
        build_image(root_key, rollback_index=OTP_ROLLBACK_MIN - 1)
    )

    bad_magic = bytearray(good)
    bad_magic[0] = ord("X")
    (out / "bad_magic.bin").write_bytes(bytes(bad_magic))

    (out / "revoked.bin").write_bytes(build_image(root_key, key_id=3))

    header_h = out / "expected.h"
    root_hex = ", ".join(f"0x{b:02x}" for b in root_hash)
    header_h.write_text(
        "/* Generated by make_images.py — do not edit. */\n"
        "#ifndef E1_TEST_EXPECTED_H\n#define E1_TEST_EXPECTED_H\n\n"
        "#include <stdint.h>\n\n"
        f"static const uint8_t TEST_ROOT_KEY_HASH[32] = {{ {root_hex} }};\n"
        f"#define TEST_OTP_ROLLBACK_MIN {OTP_ROLLBACK_MIN}u\n"
        f"#define TEST_OTP_REVOKED_BITMAP 0x{OTP_REVOKED_BITMAP:02x}u\n"
        f"#define TEST_OTP_LIFECYCLE 0x{OTP_LIFECYCLE:02x}u\n"
        "/* revoked.bin is signed by the root key but uses key_id=3. */\n"
        "#define TEST_REVOKED_BITMAP_WITH_KEY3 0x08u\n\n"
        "#endif\n"
    )
    print(f"wrote test images + expected.h to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
