/*
 * Fail-closed iOS runtime symbol shim.
 *
 * The iOS LlamaCpp.xcframework is assembled from static archives generated by
 * build-llama-cpp-mtp.mjs, not from the upstream llama-cpp-capacitor CMake
 * project. The Swift plugin still expects the historical Capacitor bridge
 * exports (`llama_init_context`, `llama_completion`, ...), and Eliza voice mode
 * expects the libelizainference ABI v1 exports.
 *
 * This file provides those ABI entry points for link/device-smoke validation.
 * It does not fake inference. Text entry points return "not loaded" until the
 * mobile bridge is wired to a real llama context, and voice entry points return
 * explicit unsupported / missing-model errors until real OmniVoice assets are
 * present in the bundle. Missing optimized kernels remain handled by the
 * generated CAPABILITIES.json gate.
 */

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "../ffi-stub/ffi.h"

#define ELIZA_INFERENCE_ABI_VERSION_STRING "1"

typedef int32_t llama_token;
typedef int32_t llama_pos;
typedef int32_t llama_seq_id;

struct llama_model_tensor_buft_override {
    const char * pattern;
    void * buft;
};

struct llama_model_kv_override;

struct llama_model_params {
    void ** devices;
    const struct llama_model_tensor_buft_override * tensor_buft_overrides;
    int32_t n_gpu_layers;
    int split_mode;
    int32_t main_gpu;
    const float * tensor_split;
    void * progress_callback;
    void * progress_callback_user_data;
    const struct llama_model_kv_override * kv_overrides;
    bool vocab_only;
    bool use_mmap;
    bool use_direct_io;
    bool use_mlock;
    bool check_tensors;
    bool use_extra_bufts;
    bool no_host;
    bool no_alloc;
};

struct llama_sampler_seq_config {
    llama_seq_id seq_id;
    void * sampler;
};

struct llama_context_params {
    uint32_t n_ctx;
    uint32_t n_batch;
    uint32_t n_ubatch;
    uint32_t n_seq_max;
    int32_t n_threads;
    int32_t n_threads_batch;
    int rope_scaling_type;
    int pooling_type;
    int attention_type;
    int flash_attn_type;
    float rope_freq_base;
    float rope_freq_scale;
    float yarn_ext_factor;
    float yarn_attn_factor;
    float yarn_beta_fast;
    float yarn_beta_slow;
    uint32_t yarn_orig_ctx;
    float defrag_thold;
    void * cb_eval;
    void * cb_eval_user_data;
    int type_k;
    int type_v;
    void * abort_callback;
    void * abort_callback_data;
    bool embeddings;
    bool offload_kqv;
    bool no_perf;
    bool op_offload;
    bool swa_full;
    bool kv_unified;
    struct llama_sampler_seq_config * samplers;
    size_t n_samplers;
};

struct llama_batch {
    int32_t n_tokens;
    llama_token * token;
    float * embd;
    llama_pos * pos;
    int32_t * n_seq_id;
    llama_seq_id ** seq_id;
    int8_t * logits;
};

extern void llama_log_set(void * log_callback, void * user_data);
extern bool llama_supports_gpu_offload(void);

struct EliInferenceContext {
    char * bundle_dir;
};

static char * eliza_dup_cstr(const char * s) {
    const char * value = s != NULL ? s : "";
    const size_t len = strlen(value);
    char * out = (char *) malloc(len + 1);
    if (out == NULL) return NULL;
    memcpy(out, value, len + 1);
    return out;
}

static char * g_last_error = NULL;

static void set_last_error(const char * msg) {
    free(g_last_error);
    g_last_error = eliza_dup_cstr(msg);
}

static void set_out_error(char ** out_error, const char * msg) {
    if (out_error != NULL) {
        *out_error = eliza_dup_cstr(msg);
    }
}

/* ---- llama-cpp-capacitor bridge exports --------------------------- */

char * llama_get_last_error(void) {
    return eliza_dup_cstr(
        g_last_error != NULL ? g_last_error : "No detailed native error captured");
}

void llama_free_string(char * value) {
    free(value);
}

int64_t llama_init_context(const char * model_path, const char * params_json) {
    (void) params_json;
    if (model_path == NULL || model_path[0] == '\0') {
        set_last_error("llama_init_context requires a model path");
    } else {
        set_last_error(
            "iOS static bridge is link-ready but real llama context wiring is not enabled in this slice");
    }
    return -1;
}

void llama_release_context(int64_t context_id) {
    (void) context_id;
}

char * llama_completion(int64_t context_id, const char * prompt, const char * params_json) {
    (void) context_id;
    (void) prompt;
    (void) params_json;
    set_last_error("Native context is not loaded");
    return eliza_dup_cstr("{\"error\":\"Native context is not loaded\"}");
}

void llama_stop_completion(int64_t context_id) {
    (void) context_id;
}

char * llama_get_formatted_chat(
    int64_t context_id,
    const char * messages,
    const char * chat_template) {
    (void) context_id;
    (void) chat_template;
    return eliza_dup_cstr(messages != NULL ? messages : "[]");
}

bool llama_toggle_native_log(bool enabled) {
    (void) enabled;
    return true;
}

float * llama_embedding(int64_t context_id, const char * text, const char * params_json) {
    (void) context_id;
    (void) text;
    (void) params_json;
    set_last_error("Native embedding context is not loaded");
    return NULL;
}

void llama_embedding_register_context(int64_t context_id, void * context) {
    (void) context_id;
    (void) context;
}

void llama_embedding_unregister_context(int64_t context_id) {
    (void) context_id;
}

char * llama_get_model_info(int64_t context_id) {
    (void) context_id;
    return eliza_dup_cstr(
        "{\"error\":\"Native context is not loaded\",\"isChatTemplateSupported\":false}");
}

void * llama_get_context_ptr(int64_t context_id) {
    (void) context_id;
    return NULL;
}

/* ---- fail-closed libelizainference exports ------------------------- */

#if !defined(ELIZA_IOS_REAL_ELIZAINFERENCE)

const char * eliza_inference_abi_version(void) {
    return ELIZA_INFERENCE_ABI_VERSION_STRING;
}

EliInferenceContext * eliza_inference_create(
    const char * bundle_dir,
    char ** out_error) {
    if (bundle_dir == NULL || bundle_dir[0] == '\0') {
        set_out_error(out_error, "[libelizainference-ios] bundle_dir is required");
        return NULL;
    }
    EliInferenceContext * ctx = (EliInferenceContext *) calloc(1, sizeof(*ctx));
    if (ctx == NULL) {
        set_out_error(out_error, "[libelizainference-ios] out of memory");
        return NULL;
    }
    ctx->bundle_dir = eliza_dup_cstr(bundle_dir);
    if (ctx->bundle_dir == NULL) {
        free(ctx);
        set_out_error(out_error, "[libelizainference-ios] out of memory");
        return NULL;
    }
    return ctx;
}

void eliza_inference_destroy(EliInferenceContext * ctx) {
    if (ctx == NULL) return;
    free(ctx->bundle_dir);
    free(ctx);
}

int eliza_inference_mmap_acquire(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (ctx == NULL) {
        set_out_error(out_error, "[libelizainference-ios] context is required");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (region_name == NULL || region_name[0] == '\0') {
        set_out_error(out_error, "[libelizainference-ios] region_name is required");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (strcmp(region_name, "text") == 0 || strcmp(region_name, "mtp") == 0) {
        return ELIZA_OK;
    }
    if (strcmp(region_name, "tts") != 0 && strcmp(region_name, "asr") != 0) {
        set_out_error(out_error, "[libelizainference-ios] unknown mmap region");
        return ELIZA_ERR_INVALID_ARG;
    }
    set_out_error(
        out_error,
        "[libelizainference-ios] voice model mmap is not loaded in this static slice");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

int eliza_inference_mmap_evict(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    (void) out_error;
    if (ctx == NULL || region_name == NULL || region_name[0] == '\0') {
        return ELIZA_ERR_INVALID_ARG;
    }
    return ELIZA_OK;
}

int eliza_inference_tts_synthesize(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    float * out_pcm,
    size_t max_samples,
    char ** out_error) {
    (void) ctx;
    (void) text;
    (void) text_len;
    (void) speaker_preset_id;
    (void) out_pcm;
    (void) max_samples;
    set_out_error(
        out_error,
        "[libelizainference-ios] real OmniVoice GGUF synthesis is not wired in this static slice");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

int eliza_inference_asr_transcribe(
    EliInferenceContext * ctx,
    const float * pcm,
    size_t n_samples,
    int sample_rate_hz,
    char * out_text,
    size_t max_text_bytes,
    char ** out_error) {
    (void) ctx;
    (void) pcm;
    (void) n_samples;
    (void) sample_rate_hz;
    if (out_text != NULL && max_text_bytes > 0) out_text[0] = '\0';
    set_out_error(out_error, "[libelizainference-ios] ASR is not wired in ABI v1");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

void eliza_inference_free_string(char * str) {
    free(str);
}

#endif

/* ---- Swift direct llama.cpp bridge helpers ------------------------ */

void eliza_llama_batch_append(
    struct llama_batch * batch,
    llama_token token,
    llama_pos pos,
    bool logits_out);

void eliza_llama_model_params_set_n_gpu_layers(
    struct llama_model_params * params,
    int32_t n) {
    if (params != NULL) params->n_gpu_layers = n;
}

void eliza_llama_context_params_set_n_ctx(
    struct llama_context_params * params,
    uint32_t n) {
    if (params != NULL) params->n_ctx = n;
}

void eliza_llama_context_params_set_n_threads(
    struct llama_context_params * params,
    int32_t n,
    int32_t n_batch) {
    if (params == NULL) return;
    params->n_threads = n;
    params->n_threads_batch = n_batch;
}

void eliza_llama_context_params_set_batch_sizes(
    struct llama_context_params * params,
    uint32_t n_batch,
    uint32_t n_ubatch) {
    if (params == NULL) return;
    params->n_batch = n_batch;
    params->n_ubatch = n_ubatch;
}

void eliza_llama_context_params_set_type_k(
    struct llama_context_params * params,
    int32_t type) {
    if (params != NULL) params->type_k = type;
}

void eliza_llama_context_params_set_type_v(
    struct llama_context_params * params,
    int32_t type) {
    if (params != NULL) params->type_v = type;
}

void eliza_llama_batch_set_single(
    struct llama_batch * batch,
    llama_token token,
    llama_pos pos,
    bool logits_out) {
    if (batch == NULL) return;
    batch->n_tokens = 0;
    eliza_llama_batch_append(batch, token, pos, logits_out);
}

void eliza_llama_batch_append(
    struct llama_batch * batch,
    llama_token token,
    llama_pos pos,
    bool logits_out) {
    if (batch == NULL) return;
    const int32_t i = batch->n_tokens;
    batch->token[i] = token;
    batch->pos[i] = pos;
    batch->n_seq_id[i] = 1;
    batch->seq_id[i][0] = 0;
    batch->logits[i] = logits_out ? 1 : 0;
    batch->n_tokens++;
}

void eliza_llama_batch_reset(struct llama_batch * batch) {
    if (batch != NULL) batch->n_tokens = 0;
}

void eliza_llama_log_silence(void) {
    llama_log_set(NULL, NULL);
}

bool eliza_llama_has_metal(void) {
    return llama_supports_gpu_offload();
}

bool eliza_llama_speculative_supported(void) {
    return false;
}

int32_t eliza_llama_speculative_draft_gen(
    void * target_ctx,
    void * drafter_ctx,
    const llama_token * past_tokens,
    int32_t n_past,
    int32_t draft_min,
    int32_t draft_max,
    llama_token * out_drafted,
    int32_t out_capacity) {
    (void) target_ctx;
    (void) drafter_ctx;
    (void) past_tokens;
    (void) n_past;
    (void) draft_min;
    (void) draft_max;
    (void) out_drafted;
    (void) out_capacity;
    return 0;
}

void * eliza_llama_sampler_init_token_tree(
    int32_t n_vocab,
    const uint8_t * trie_bytes,
    size_t trie_size) {
    (void) n_vocab;
    (void) trie_bytes;
    (void) trie_size;
    return NULL;
}
