/**
 * Local content-addressed media store for chat attachments.
 *
 * Bytes uploaded by the user or generated by the agent are written under
 * `${STATE_DIR}/media/<sha256>.<ext>` and referenced by a served
 * `/api/media/<sha256>.<ext>` URL. Content addressing gives free
 * de-duplication: the same image attached twice is stored once and reuses its
 * description cache (keyed on the same hash), and only a compact served URL —
 * never raw base64 — lands in the message record or the agent's context.
 *
 * The sha256 filename is an unguessable capability, so media is served before
 * the auth gate (like static assets); `<img>`/`<audio>` requests carry no auth
 * header. `serveMediaFile` only ever serves names matching the strict
 * content-addressed pattern from the dedicated media directory.
 */

import crypto from "node:crypto";
import fs from "node:fs";
import type http from "node:http";
import path from "node:path";
import { logger } from "@elizaos/core";
import { resolveStateDir } from "../config/paths.ts";
import { generateThumbnailBytes } from "./media-thumbnail.ts";

const EXT_BY_MIME: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/jpg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/avif": "avif",
  "image/bmp": "bmp",
  "image/svg+xml": "svg",
  "audio/mpeg": "mp3",
  "audio/mp3": "mp3",
  "audio/wav": "wav",
  "audio/x-wav": "wav",
  "audio/wave": "wav",
  "audio/ogg": "ogg",
  "audio/webm": "weba",
  "audio/mp4": "m4a",
  "audio/aac": "aac",
  "audio/flac": "flac",
  "video/mp4": "mp4",
  "video/webm": "webm",
  "video/quicktime": "mov",
  "video/ogg": "ogv",
  "application/pdf": "pdf",
  "text/plain": "txt",
  "text/csv": "csv",
  "text/markdown": "md",
  "application/json": "json",
};

const MIME_BY_EXT: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  gif: "image/gif",
  avif: "image/avif",
  bmp: "image/bmp",
  svg: "image/svg+xml",
  mp3: "audio/mpeg",
  wav: "audio/wav",
  ogg: "audio/ogg",
  oga: "audio/ogg",
  weba: "audio/webm",
  m4a: "audio/mp4",
  aac: "audio/aac",
  flac: "audio/flac",
  mp4: "video/mp4",
  webm: "video/webm",
  mov: "video/quicktime",
  ogv: "video/ogg",
  pdf: "application/pdf",
  txt: "text/plain; charset=utf-8",
  csv: "text/csv; charset=utf-8",
  md: "text/markdown; charset=utf-8",
  json: "application/json; charset=utf-8",
  bin: "application/octet-stream",
};

/** Strict content-addressed name: 64-hex sha256 + short alphanumeric extension. */
const MEDIA_FILE_NAME = /^[a-f0-9]{64}\.[a-z0-9]{1,8}$/;

const MEDIA_URL_PREFIX = "/api/media/";

let cachedMediaDir: string | null = null;

function mediaDir(): string {
  if (cachedMediaDir) return cachedMediaDir;
  const dir = path.join(resolveStateDir(), "media");
  fs.mkdirSync(dir, { recursive: true });
  cachedMediaDir = dir;
  return dir;
}

function extForMime(mimeType: string): string {
  return EXT_BY_MIME[mimeType.trim().toLowerCase()] ?? "bin";
}

// ---------------------------------------------------------------------------
// Size-capped eviction
// ---------------------------------------------------------------------------

const DEFAULT_MAX_STORE_BYTES = 2 * 1024 * 1024 * 1024; // 2 GB
const EVICT_INTERVAL_MS = 30_000;
let lastEvictAt = 0;

function maxStoreBytes(): number {
  const raw = process.env.ELIZA_MEDIA_STORE_MAX_BYTES;
  const parsed = raw ? Number.parseInt(raw, 10) : Number.NaN;
  return Number.isFinite(parsed) && parsed > 0
    ? parsed
    : DEFAULT_MAX_STORE_BYTES;
}

export interface MediaFileStat {
  name: string;
  size: number;
  mtimeMs: number;
}

/**
 * Pure eviction policy: given the current files and a byte cap, return the
 * names to delete (oldest-by-mtime first) so the store drops to 90% of the
 * cap. Returns [] when already within budget. Exported for unit tests.
 */
export function selectMediaToEvict(
  files: MediaFileStat[],
  cap: number,
): string[] {
  let total = files.reduce((sum, file) => sum + file.size, 0);
  if (total <= cap) return [];
  const target = Math.floor(cap * 0.9);
  const oldestFirst = [...files].sort((a, b) => a.mtimeMs - b.mtimeMs);
  const evict: string[] = [];
  for (const file of oldestFirst) {
    if (total <= target) break;
    evict.push(file.name);
    total -= file.size;
  }
  return evict;
}

/**
 * Best-effort FIFO eviction so the local media store never grows without
 * bound. Throttled to once per {@link EVICT_INTERVAL_MS}; when the directory
 * exceeds the cap it deletes oldest-by-mtime files down to 90% of the cap.
 * Content is immutable + content-addressed, so an evicted file simply re-saves
 * if the same bytes are uploaded again. A message that references evicted media
 * renders a broken tile — the cap defaults to 2 GB so this only bites under
 * heavy use, and is tunable via `ELIZA_MEDIA_STORE_MAX_BYTES`.
 */
function maybeEvict(): void {
  const now = Date.now();
  if (now - lastEvictAt < EVICT_INTERVAL_MS) return;
  lastEvictAt = now;
  try {
    const dir = mediaDir();
    const files: MediaFileStat[] = [];
    for (const name of fs.readdirSync(dir)) {
      try {
        const stat = fs.statSync(path.join(dir, name));
        if (!stat.isFile()) continue;
        files.push({ name, size: stat.size, mtimeMs: stat.mtimeMs });
      } catch {
        // file vanished mid-scan — ignore
      }
    }
    const evict = selectMediaToEvict(files, maxStoreBytes());
    let evicted = 0;
    for (const name of evict) {
      try {
        fs.unlinkSync(path.join(dir, name));
        evicted += 1;
      } catch {
        // ignore
      }
    }
    if (evicted > 0) {
      logger.info(`[media-store] evicted ${evicted} file(s) over size cap`);
    }
  } catch (err) {
    logger.warn(
      `[media-store] eviction scan failed: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
}

export interface PersistedMedia {
  /** Served URL (`/api/media/<sha256>.<ext>`) for the stored bytes. */
  url: string;
  /** sha256 of the bytes — also the description-cache key. */
  hash: string;
  fileName: string;
}

/** Write bytes to the content-addressed store (idempotent) and return the served URL. */
export function persistMediaBytes(
  buffer: Buffer,
  mimeType: string,
): PersistedMedia {
  const hash = crypto.createHash("sha256").update(buffer).digest("hex");
  const fileName = `${hash}.${extForMime(mimeType)}`;
  const filePath = path.join(mediaDir(), fileName);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, buffer);
    maybeEvict();
  }
  return { url: `${MEDIA_URL_PREFIX}${fileName}`, hash, fileName };
}

const DATA_URL_RE = /^data:([^;,]*)(;base64)?,([\s\S]*)$/;

/** Persist a `data:` URL's bytes to the store; returns null for non-data URLs. */
export function persistDataUrl(dataUrl: string): PersistedMedia | null {
  const match = DATA_URL_RE.exec(dataUrl.trim());
  if (!match) return null;
  const mimeType = match[1] || "application/octet-stream";
  const isBase64 = Boolean(match[2]);
  const payload = match[3] ?? "";
  let buffer: Buffer;
  try {
    buffer = isBase64
      ? Buffer.from(payload, "base64")
      : Buffer.from(decodeURIComponent(payload), "utf8");
  } catch {
    return null;
  }
  if (buffer.length === 0) return null;
  return persistMediaBytes(buffer, mimeType);
}

/** True when a URL already points at this store (no need to re-persist). */
export function isStoredMediaUrl(url: string): boolean {
  return url.startsWith(MEDIA_URL_PREFIX);
}

/** Extract the stored filename (`<sha256>.<ext>`) from a served media URL, else null. */
export function mediaFileNameFromUrl(url: string): string | null {
  if (typeof url !== "string" || !url.startsWith(MEDIA_URL_PREFIX)) return null;
  const name = url.slice(MEDIA_URL_PREFIX.length).split(/[?#]/)[0] ?? "";
  return MEDIA_FILE_NAME.test(name) ? name : null;
}

// Orphan GC grace: never delete files younger than this, so media that was just
// persisted but not yet referenced by a saved message (or just served) survives.
const GC_MIN_AGE_MS = 60 * 60 * 1000;

/**
 * Delete stored media files not referenced by any live attachment. `referenced`
 * is the set of `<sha256>.<ext>` filenames still in use (built from message
 * attachment URLs via {@link mediaFileNameFromUrl}). Files younger than the
 * grace window are kept. Best-effort; returns counts.
 */
export function gcUnreferencedMedia(referenced: Set<string>): {
  removed: number;
  scanned: number;
} {
  let removed = 0;
  let scanned = 0;
  try {
    const dir = mediaDir();
    const now = Date.now();
    for (const name of fs.readdirSync(dir)) {
      if (!MEDIA_FILE_NAME.test(name)) continue;
      scanned += 1;
      if (referenced.has(name)) continue;
      try {
        const stat = fs.statSync(path.join(dir, name));
        if (now - stat.mtimeMs < GC_MIN_AGE_MS) continue; // grace window
        fs.unlinkSync(path.join(dir, name));
        removed += 1;
      } catch {
        // ignore individual file errors
      }
    }
  } catch (err) {
    logger.warn(
      `[media-store] GC scan failed: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
  if (removed > 0) {
    logger.info(
      `[media-store] GC removed ${removed} unreferenced file(s) of ${scanned}`,
    );
  }
  return { removed, scanned };
}

function mimeForFile(fileName: string): string {
  const ext = fileName.split(".").pop()?.toLowerCase() ?? "bin";
  return MIME_BY_EXT[ext] ?? "application/octet-stream";
}

// Touch-on-serve → LRU: bump the file's mtime when it's served so eviction
// (oldest-mtime-first) keeps frequently-viewed media and drops the truly cold
// files. Throttled per file so a burst of range requests doesn't thrash the fs.
const TOUCH_THROTTLE_MS = 60_000;
const lastTouchedAt = new Map<string, number>();

function touchOnServe(filePath: string): void {
  const now = Date.now();
  if (now - (lastTouchedAt.get(filePath) ?? 0) < TOUCH_THROTTLE_MS) return;
  lastTouchedAt.set(filePath, now);
  try {
    const stamp = new Date(now);
    fs.utimesSync(filePath, stamp, stamp);
  } catch {
    // best-effort — atime/mtime updates can fail on some filesystems
  }
}

interface ResolvedMediaFile {
  filePath: string;
  size: number;
  contentType: string;
}

/**
 * Validate a `/api/media/<name>` path and stat the file, bumping its mtime for
 * LRU. Returns the resolved file or an HTTP status (400 bad name, 404 missing).
 * Shared by the HTTP serve path and the in-process (iOS IPC) route handler.
 */
function resolveMediaFile(
  pathname: string,
): ResolvedMediaFile | { error: number } {
  let name: string;
  try {
    name = decodeURIComponent(pathname.slice(MEDIA_URL_PREFIX.length));
  } catch {
    return { error: 400 };
  }
  if (!MEDIA_FILE_NAME.test(name)) return { error: 400 };
  const filePath = path.join(mediaDir(), name);
  // Defence in depth against traversal — name is already pattern-validated.
  if (path.dirname(filePath) !== mediaDir()) return { error: 400 };
  let stat: fs.Stats;
  try {
    stat = fs.statSync(filePath);
    if (!stat.isFile()) throw new Error("not a file");
  } catch {
    return { error: 404 };
  }
  touchOnServe(filePath);
  return { filePath, size: stat.size, contentType: mimeForFile(name) };
}

/**
 * Serve a media file for the IN-PROCESS route path (iOS, where no HTTP server
 * runs and requests are dispatched over `runtime.routes`). Returns a
 * RouteHandlerResult-shaped object with a `Buffer` body; the native bridge
 * base64-encodes it losslessly. No Range support — the in-process path buffers
 * the whole file, which is fine for local on-device media.
 */
export function handleMediaRouteRequest(
  pathname: string,
  method: string,
): { status: number; headers: Record<string, string>; body?: Buffer } {
  const TEXT = { "Content-Type": "text/plain; charset=utf-8" };
  if (method !== "GET" && method !== "HEAD") {
    return {
      status: 405,
      headers: TEXT,
      body: Buffer.from("Method not allowed"),
    };
  }
  const resolved = resolveMediaFile(pathname);
  if ("error" in resolved) {
    return {
      status: resolved.error,
      headers: TEXT,
      body: Buffer.from(
        resolved.error === 400 ? "Bad media name" : "Not found",
      ),
    };
  }
  const headers: Record<string, string> = {
    "Content-Type": resolved.contentType,
    "Cache-Control": "public, max-age=31536000, immutable",
    "Content-Length": String(resolved.size),
  };
  if (method === "HEAD") return { status: 200, headers };
  return { status: 200, headers, body: fs.readFileSync(resolved.filePath) };
}

/**
 * Serve a stored media file for `GET/HEAD /api/media/<name>`. Returns true when
 * the request was handled (including 404/400). Supports HTTP Range so `<video>`
 * / `<audio>` seeking works. Bytes are immutable (content-addressed) so they
 * carry a long immutable Cache-Control.
 */
export function serveMediaFile(
  req: http.IncomingMessage,
  res: http.ServerResponse,
  pathname: string,
): boolean {
  if (!pathname.startsWith(MEDIA_URL_PREFIX)) return false;
  const method = req.method ?? "GET";
  if (method !== "GET" && method !== "HEAD") return false;

  const resolved = resolveMediaFile(pathname);
  if ("error" in resolved) {
    res.writeHead(resolved.error, {
      "Content-Type": "text/plain; charset=utf-8",
    });
    res.end(resolved.error === 400 ? "Bad media name" : "Not found");
    return true;
  }
  const { filePath, size, contentType } = resolved;

  const baseHeaders: Record<string, string | number> = {
    "Content-Type": contentType,
    "Cache-Control": "public, max-age=31536000, immutable",
    "Accept-Ranges": "bytes",
  };

  const range = req.headers.range;
  if (range && method === "GET") {
    const match = /^bytes=(\d*)-(\d*)$/.exec(range.trim());
    if (match) {
      const startRaw = match[1];
      const endRaw = match[2];
      let start = startRaw ? Number.parseInt(startRaw, 10) : 0;
      let end = endRaw ? Number.parseInt(endRaw, 10) : size - 1;
      if (!startRaw && endRaw) {
        // suffix range: last N bytes
        start = Math.max(0, size - Number.parseInt(endRaw, 10));
        end = size - 1;
      }
      if (
        Number.isNaN(start) ||
        Number.isNaN(end) ||
        start > end ||
        start >= size
      ) {
        res.writeHead(416, {
          "Content-Range": `bytes */${size}`,
          "Content-Type": "text/plain; charset=utf-8",
        });
        res.end("Range not satisfiable");
        return true;
      }
      end = Math.min(end, size - 1);
      res.writeHead(206, {
        ...baseHeaders,
        "Content-Range": `bytes ${start}-${end}/${size}`,
        "Content-Length": end - start + 1,
      });
      fs.createReadStream(filePath, { start, end }).pipe(res);
      return true;
    }
  }

  res.writeHead(200, { ...baseHeaders, "Content-Length": size });
  if (method === "HEAD") {
    res.end();
    return true;
  }
  fs.createReadStream(filePath).pipe(res);
  return true;
}

/**
 * Generate a downscaled thumbnail from raw image bytes and persist it as its
 * own store entry. Returns the thumbnail's served URL, or null when the image
 * isn't thumbnailable / already small / the resizer is unavailable. Best-effort.
 */
export async function persistImageThumbnail(
  source: Buffer,
  srcMimeType: string,
): Promise<string | null> {
  try {
    const thumb = await generateThumbnailBytes(source, srcMimeType);
    if (!thumb) return null;
    return persistMediaBytes(thumb.buffer, thumb.mimeType).url;
  } catch {
    return null;
  }
}

/**
 * Pre-compute a thumbnail for an already-stored image file (e.g. an
 * agent-generated image just persisted from a data: URL). Reads the stored
 * bytes, downscales, and persists the thumbnail. Returns its served URL or null.
 */
export async function ensureThumbnailForStoredFile(
  fileName: string,
): Promise<string | null> {
  if (!MEDIA_FILE_NAME.test(fileName)) return null;
  const srcMime = mimeForFile(fileName);
  if (!srcMime.startsWith("image/")) return null;
  let buffer: Buffer;
  try {
    buffer = fs.readFileSync(path.join(mediaDir(), fileName));
  } catch {
    return null;
  }
  return persistImageThumbnail(buffer, srcMime);
}

/** Best-effort: convert a `data:` URL on an attachment to a stored served URL. */
export function persistAttachmentUrlIfInline(url: string): string {
  if (!url.startsWith("data:")) return url;
  try {
    const persisted = persistDataUrl(url);
    return persisted?.url ?? url;
  } catch (err) {
    logger.warn(
      `[media-store] failed to persist inline data URL: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
    return url;
  }
}
