import type { Plugin } from "@elizaos/core";

export const walletAppPlugin: Plugin = {
  name: "@elizaos/plugin-wallet-ui",
  description: "Non-custodial wallet inventory UI",
  app: {
    displayName: "Wallet",
    category: "wallet",
    icon: "Wallet",
    visibleInAppStore: true,
    developerOnly: false,
    navTabs: [
      {
        id: "wallet.inventory",
        label: "Wallet",
        icon: "Wallet",
        path: "/inventory",
        order: 50,
        componentExport: "@elizaos/plugin-wallet-ui#InventoryView",
      },
    ],
  },
  views: [
    {
      id: "wallet",
      label: "Wallet",
      description: "Non-custodial wallet inventory and token balances",
      icon: "Wallet",
      path: "/wallet",
      bundlePath: "dist/views/bundle.js",
      componentExport: "InventoryView",
      tags: ["finance", "crypto", "wallet"],
      visibleInManager: true,
      desktopTabEnabled: true,
    },
    {
      id: "wallet",
      label: "Wallet XR",
      description: "Non-custodial wallet inventory and token balances",
      icon: "Wallet",
      path: "/wallet",
      viewType: "xr",
      bundlePath: "dist/views/bundle.js",
      componentExport: "InventoryView",
      tags: ["finance", "crypto", "wallet"],
      visibleInManager: true,
      desktopTabEnabled: true,
    },
    {
      id: "wallet",
      label: "Wallet TUI",
      description: "Terminal wallet inventory and balance surface",
      icon: "Wallet",
      path: "/wallet/tui",
      viewType: "tui",
      bundlePath: "dist/views/bundle.js",
      componentExport: "InventoryTuiView",
      tags: ["finance", "crypto", "wallet", "terminal"],
      visibleInManager: true,
      desktopTabEnabled: true,
    },
  ],
  widgets: [
    {
      id: "wallet.status",
      pluginId: "wallet",
      slot: "chat-sidebar",
      label: "Wallet Status",
      icon: "Wallet",
      order: 70,
      defaultEnabled: true,
    },
  ],
};
