/* Minimal checked-in Linux contract for the hello NPU smoke path. */
#ifndef HELLO_PLATFORM_CONTRACT_H
#define HELLO_PLATFORM_CONTRACT_H

#define HELLO_CONTRACT_VERSION 1u
#define HELLO_IMPLEMENTED_WINDOW_BYTES 256u
#define HELLO_NPU_BASE 0x10020000u

#define HELLO_NPU_OP_A_OFFSET 0x00u
#define HELLO_NPU_OP_B_OFFSET 0x04u
#define HELLO_NPU_RESULT_OFFSET 0x08u
#define HELLO_NPU_CTRL_STATUS_OFFSET 0x0Cu
#define HELLO_NPU_OPCODE_OFFSET 0x10u
#define HELLO_NPU_ACC_OFFSET 0x14u
#define HELLO_NPU_GEMM_CFG_OFFSET 0x20u
#define HELLO_NPU_GEMM_BASE_OFFSET 0x24u
#define HELLO_NPU_GEMM_STRIDE_OFFSET 0x28u
#define HELLO_NPU_PERF_UNSUPPORTED_OPS_OFFSET 0x2Cu
#define HELLO_NPU_CMD_PARAM_OFFSET 0x30u
#define HELLO_NPU_DESC_BASE_OFFSET 0x40u
#define HELLO_NPU_DESC_HEAD_OFFSET 0x44u
#define HELLO_NPU_DESC_TAIL_OFFSET 0x48u
#define HELLO_NPU_DESC_STATUS_OFFSET 0x4Cu
#define HELLO_NPU_PERF_CYCLES_OFFSET 0x50u
#define HELLO_NPU_PERF_MACS_OFFSET 0x54u
#define HELLO_NPU_PERF_OPS_OFFSET 0x58u
#define HELLO_NPU_PERF_ERRORS_OFFSET 0x5Cu
#define HELLO_NPU_DESC_TIMEOUT_COUNT_OFFSET 0x60u
#define HELLO_NPU_DESC_BYTES_READ_OFFSET 0x64u
#define HELLO_NPU_SCRATCH0_OFFSET 0x80u

#endif
