/**
 * TelegramBot — human-in-the-loop content approval via Telegram.
 *
 * FLOW:
 *   1. Content is generated by AI → status: "pending_approval"
 *   2. Telegram bot sends a message: "New post ready for {Agency Name}"
 *   3. Business owner clicks: [✅ Approve] [✏️ Edit] [❌ Reject]
 *   4. On approve → published via Zernio
 *   5. On edit → opens web dashboard for manual editing
 *   6. On reject → logs feedback, regenerates
 *
 * Uses Telegram Bot API (completely free, no API costs).
 * Each agency owner connects their Telegram account during onboarding.
 */

export interface TelegramConfig {
  botToken: string;
  /** Whether the bot is active. */
  enabled: boolean;
  /** Default chat IDs to notify (per tenant). */
  tenantChats: Map<string, string>;
}

export interface ContentNotification {
  contentId: string;
  tenantId: string;
  tenantName: string;
  title: string;
  excerpt: string;
  platform: string;
  contentType: string;
  imageUrl?: string;
  scheduledDate?: string;
}

export interface ApprovalAction {
  contentId: string;
  tenantId: string;
  chatId: string;
  action: "approved" | "edit" | "rejected";
  feedback?: string;
}

// ── Telegram Bot API types ─────────────────────────────────────────────

interface TelegramMessage {
  message_id: number;
  chat: { id: number; type: string };
  text?: string;
  callback_query?: {
    id: string;
    from: { id: number };
    message: { message_id: number; chat: { id: number } };
    data: string;
  };
}

// ── Service ────────────────────────────────────────────────────────────

export class TelegramBot {
  private config: TelegramConfig;
  /** Inline keyboard action → handler. */
  private actionHandlers = new Map<
    string,
    (action: ApprovalAction) => Promise<void>
  >();
  /** Polling interval reference. */
  private pollInterval: ReturnType<typeof setInterval> | null = null;
  /** Last processed update ID (for polling). */
  private lastUpdateId = 0;

  constructor(config: TelegramConfig) {
    this.config = config;
  }

  // ── Lifecycle ────────────────────────────────────────────────────────

  /** Start the bot — begins polling for updates. */
  start(): void {
    if (!this.config.enabled) {
      console.log("[telegram] Bot disabled — set TELEGRAM_BOT_TOKEN to enable");
      return;
    }
    console.log("[telegram] Bot started — polling for approvals");
    this.pollInterval = setInterval(() => this.poll(), 2000);
  }

  /** Stop the bot. */
  stop(): void {
    if (this.pollInterval) {
      clearInterval(this.pollInterval);
      this.pollInterval = null;
    }
    console.log("[telegram] Bot stopped");
  }

  /** Register handler for incoming approval actions. */
  onAction(handler: (action: ApprovalAction) => Promise<void>): void {
    this.actionHandlers.set("default", handler);
  }

  // ── Sending ──────────────────────────────────────────────────────────

  /**
   * Send a content approval notification to a tenant's Telegram chat.
   * Returns the message ID for later editing/updating.
   */
  async sendContentForApproval(
    chatId: string,
    notification: ContentNotification,
  ): Promise<number | null> {
    if (!this.config.enabled) return null;

    const caption = this.buildApprovalMessage(notification);
    const keyboard = this.buildApprovalKeyboard(notification);

    try {
      const msg = await this.apiCall("sendMessage", {
        chat_id: chatId,
        text: caption,
        parse_mode: "HTML",
        reply_markup: JSON.stringify(keyboard),
      });

      if (notification.imageUrl) {
        // Send image separately with caption
        await this.apiCall("sendPhoto", {
          chat_id: chatId,
          photo: notification.imageUrl,
          caption,
          parse_mode: "HTML",
          reply_markup: JSON.stringify(keyboard),
        });
      }

      console.log(`[telegram] Approval sent for ${notification.contentId}`);
      return (msg as TelegramMessage)?.message_id ?? null;
    } catch (e: any) {
      console.error(`[telegram] Failed to send: ${e.message}`);
      return null;
    }
  }

  /**
   * Send a generic message to a chat.
   */
  async sendMessage(chatId: string, text: string): Promise<boolean> {
    if (!this.config.enabled) return false;
    try {
      await this.apiCall("sendMessage", {
        chat_id: chatId,
        text,
        parse_mode: "HTML",
      });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Update an existing approval message (e.g., after action taken).
   */
  async updateApprovalMessage(
    chatId: string,
    messageId: number,
    newText: string,
  ): Promise<void> {
    if (!this.config.enabled) return;
    try {
      await this.apiCall("editMessageText", {
        chat_id: chatId,
        message_id: messageId,
        text: newText,
        parse_mode: "HTML",
      });
    } catch (e: any) {
      console.error(`[telegram] Failed to update: ${e.message}`);
    }
  }

  /**
   * Send a daily digest of pending content.
   */
  async sendDailyDigest(
    chatId: string,
    pending: ContentNotification[],
  ): Promise<void> {
    if (!this.config.enabled || pending.length === 0) return;

    const lines = [
      "📋 <b>Daily Content Digest</b>",
      "",
      `${pending.length} posts waiting for your approval:`,
      "",
      ...pending.map(
        (p, i) =>
          `${i + 1}. <b>${p.title}</b>\n   ${p.platform} · ${p.contentType} · ${p.scheduledDate ?? "unscheduled"}`,
      ),
      "",
      "Reply with the number to approve, or open the dashboard to review all.",
    ];

    await this.sendMessage(chatId, lines.join("\n"));
  }

  // ── Polling ──────────────────────────────────────────────────────────

  private async poll(): Promise<void> {
    try {
      const updates = (await this.apiCall("getUpdates", {
        offset: this.lastUpdateId + 1,
        timeout: 5,
      })) as {
        result?: Array<{
          update_id: number;
          message?: {
            message_id: number;
            text?: string;
            chat: { id: number };
            from?: { first_name?: string };
          };
          callback_query?: {
            id: string;
            data: string;
            from: { id: number };
            message: { message_id: number; chat: { id: number } };
          };
        }>;
      };

      if (!updates?.result) return;

      for (const update of updates.result) {
        this.lastUpdateId = Math.max(this.lastUpdateId, update.update_id);

        if (update.callback_query?.data) {
          await this.handleCallback(update.callback_query);
        }

        // Handle /start and other text messages
        if (update.message?.text && update.message?.chat?.id) {
          const chatId = String(update.message.chat.id);
          const text = update.message.text.trim();

          if (text === "/start") {
            const username = update.message.from?.first_name ?? "there";
            await this.sendMessage(
              chatId,
              `👋 Welcome ${username}!\n\nI'm your Optimus content approval bot. When your AI generates new posts, I'll send them here for you to review.\n\nTap:\n✅ Approve & Publish\n✏️ Edit First\n❌ Reject & Regenerate\n\nYour chat ID: ${chatId}\n\nThis is already linked — you'll get notifications automatically.`,
            );
            // Auto-link: store this chat ID for the first available tenant
            this.config.tenantChats.set("demo-tenant", chatId);
            console.log(
              `[telegram] /start from chat ${chatId} — linked to demo-tenant`,
            );
          } else {
            await this.sendMessage(
              chatId,
              "I'm a content approval bot. I'll send you posts to review when they're ready. You don't need to message me — just wait for notifications.",
            );
          }
        }
      }
    } catch {
      // Silently ignore polling errors (bot token not set, network, etc.)
    }
  }

  // ── Callback handling ────────────────────────────────────────────────

  private async handleCallback(callback: {
    id: string;
    data: string;
    from: { id: number };
    message: { message_id: number; chat: { id: number } };
  }): Promise<void> {
    // Parse callback data: "approve:content_123:tenant_456"
    const parts = callback.data.split(":");
    const action = parts[0] as "approve" | "edit" | "reject";
    const contentId = parts[1] ?? "unknown";
    const tenantId = parts[2] ?? "unknown";

    const dashboardUrl = process.env.DASHBOARD_URL ?? "http://localhost:3000";
    const reviewUrl = `${dashboardUrl}/dashboard/content/${contentId}`;
    const calendarUrl = `${dashboardUrl}/dashboard/calendar`;
    const libraryUrl = `${dashboardUrl}/dashboard/content`;

    // Build response message with links based on action
    let responseText = "";
    let ackText = "";

    if (action === "approve") {
      ackText = "✅ Approved!";
      responseText = `✅ <b>APPROVED</b> — Post will be published\n\n<a href="${reviewUrl}">📝 View post on dashboard</a>\n<a href="${calendarUrl}">📅 Check calendar</a>`;
    } else if (action === "edit") {
      ackText = "Opening editor...";
      responseText = `✏️ <b>EDIT</b> — Open the link below to edit this post\n\n👉 <a href="${reviewUrl}">Edit this post on the dashboard</a>`;
    } else {
      ackText = "❌ Rejected. Will regenerate.";
      responseText = `❌ <b>REJECTED</b> — Post will be regenerated\n\n<a href="${libraryUrl}">📂 View content library</a>\n<a href="${reviewUrl}">🔁 Regenerate from dashboard</a>`;
    }

    // Acknowledge the callback
    await this.apiCall("answerCallbackQuery", {
      callback_query_id: callback.id,
      text: ackText,
    });

    // Update the message to show action + links
    await this.apiCall("editMessageText", {
      chat_id: callback.message.chat.id,
      message_id: callback.message.message_id,
      text: responseText,
      parse_mode: "HTML",
      disable_web_page_preview: false,
    });

    // Dispatch to registered handlers
    const approvalAction: ApprovalAction = {
      contentId,
      tenantId,
      chatId: String(callback.message.chat.id),
      action:
        action === "approve"
          ? "approved"
          : action === "edit"
            ? "edit"
            : "rejected",
    };

    const handler = this.actionHandlers.get("default");
    if (handler) {
      await handler(approvalAction);
    }
  }

  // ── Message building ─────────────────────────────────────────────────

  private buildApprovalMessage(n: ContentNotification): string {
    const lines = [
      `🤖 <b>New Content Ready!</b>`,
      `📱 <b>Agency:</b> ${n.tenantName}`,
      ``,
      `📝 <b>${n.title}</b>`,
      ``,
      n.excerpt.slice(0, 300),
      ``,
      `📌 <b>Platform:</b> ${n.platform}`,
      `📄 <b>Type:</b> ${n.contentType}`,
    ];

    if (n.scheduledDate) {
      lines.push(`📅 <b>Scheduled:</b> ${n.scheduledDate}`);
    }

    lines.push(``);
    lines.push(`👇 <b>What do you want to do?</b>`);

    return lines.join("\n");
  }

  private buildApprovalKeyboard(n: ContentNotification) {
    const data = (action: string) => `${action}:${n.contentId}:${n.tenantId}`;

    return {
      inline_keyboard: [
        [{ text: "✅ Approve & Publish", callback_data: data("approve") }],
        [{ text: "✏️ Edit First", callback_data: data("edit") }],
        [{ text: "❌ Reject & Regenerate", callback_data: data("reject") }],
      ],
    };
  }

  // ── Telegram API helper ──────────────────────────────────────────────

  private async apiCall(
    method: string,
    params: Record<string, unknown>,
  ): Promise<unknown> {
    const url = `https://api.telegram.org/bot${this.config.botToken}/${method}`;
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(params),
      });
      return res.json();
    } catch (e: any) {
      console.error(`[telegram] API error (${method}): ${e.message}`);
      return null;
    }
  }
}

// ── Factory ────────────────────────────────────────────────────────────

let instance: TelegramBot | null = null;

export function getTelegramBot(): TelegramBot {
  if (!instance) {
    const token = process.env.TELEGRAM_BOT_TOKEN;
    instance = new TelegramBot({
      botToken: token ?? "",
      enabled: !!token,
      tenantChats: new Map(),
    });
  }
  return instance;
}

/**
 * Link a tenant to a Telegram chat ID.
 * Called during onboarding when the user sends /start to the bot.
 */
export function linkTenantChat(tenantId: string, chatId: string): void {
  const bot = getTelegramBot();
  // Access private config to store mapping
  (bot as any).config.tenantChats.set(tenantId, chatId);
}

export function getTenantChat(tenantId: string): string | undefined {
  return getTelegramBot().config.tenantChats.get(tenantId);
}
