/**
 * OWNER_REMINDERS — calendar-style reminders (Apple Reminders / Google Tasks
 * bridges + native reminders generated by the agent).
 *
 * STUB. Handler lives at
 *   plugins/plugin-personal-assistant/src/actions/owner-surfaces.ts. Follow-up generation
 *   logic is in plugins/plugin-personal-assistant/src/followup/ (followup-tracker.ts and
 *   actions/). Native bridges are kept in their own packages
 *   (@elizaos/macosreminders, plugin-google).
 */

import type {
  Action,
  ActionResult,
  HandlerCallback,
  HandlerOptions,
  IAgentRuntime,
  Memory,
  State,
} from "@elizaos/core";

import {
  GOALS_CONTEXTS,
  GOALS_LOG_PREFIX,
  REMINDER_ACTIONS,
} from "../types.ts";

export const ownerRemindersAction: Action = {
  name: "OWNER_REMINDERS",
  description:
    "Manage the owner's reminders. Actions: create, update, delete, complete, snooze, list. Bridges to Apple Reminders + Google Tasks live in their respective plugins; this action is the owner-facing surface.",
  descriptionCompressed:
    "owner reminders: create|update|delete|complete|snooze|list",
  contexts: [...GOALS_CONTEXTS],
  contextGate: { anyOf: [...GOALS_CONTEXTS] },
  roleGate: { minRole: "ADMIN" },
  tags: [
    "domain:reminders",
    "capability:write",
    "capability:update",
    "capability:delete",
    "surface:owner",
  ],
  similes: ["REMIND", "REMIND_ME", "REMINDER", "FOLLOWUP", "FOLLOW_UP"],
  parameters: [
    {
      name: "action",
      description:
        "Action: create | update | delete | complete | snooze | list.",
      required: true,
      schema: { type: "string" as const, enum: [...REMINDER_ACTIONS] },
    },
    {
      name: "id",
      description: "Reminder id.",
      required: false,
      schema: { type: "string" as const },
    },
    {
      name: "title",
      description: "Reminder title (create/update).",
      required: false,
      schema: { type: "string" as const },
    },
    {
      name: "dueAt",
      description: "ISO-8601 due timestamp (create/update/snooze).",
      required: false,
      schema: { type: "string" as const },
    },
  ],
  validate: async (_runtime: IAgentRuntime): Promise<boolean> => true,
  handler: async (
    _runtime: IAgentRuntime,
    _message: Memory,
    _state?: State,
    _options?: HandlerOptions,
    _callback?: HandlerCallback,
  ): Promise<ActionResult> => {
    // TODO(migrate): port the OWNER_REMINDERS handler from
    // plugins/plugin-personal-assistant/src/actions/owner-surfaces.ts. The follow-up
    // watcher in plugins/plugin-personal-assistant/src/followup/followup-tracker.ts
    // should move into a sibling src/followup/ folder here.
    return {
      success: false,
      text: `${GOALS_LOG_PREFIX} OWNER_REMINDERS not yet implemented (scaffold stub)`,
      data: { action: "noop", reason: "scaffold_stub" },
    };
  },
};
