#!/usr/bin/env python3
"""rot-integration-check gate (W1).

Fail-closed gate for the E1 root-of-trust integration top
(rtl/security/rot/e1_rot_top.sv) per docs/security/tee-plan/02-root-of-trust.md
S8. Writes build/reports/rot_integration.json in the eliza.gate_status.v1 shape.

PASS requires ALL of:
  (a) the OpenTitan pin manifest resolves: the checkout is present and its HEAD
      matches external/opentitan/pin-manifest.json (Apache-2.0, Earl Grey tag);
  (b) e1_rot_top elaborates clean under Verilator -- the spine-only build, the
      Ibex-instantiated build, and the integrated build with every real
      OpenTitan crypto block (e1_rot_ot_<block> harness) instantiated;
  (c) the cocotb reset-release + mailbox tests pass.

It reports the real-vs-shim block inventory and FAILS CLOSED (status BLOCKED)
for every crypto/security block that is shimmed rather than truly elaborated,
naming the missing dependency. This is the project's fail-closed law (CLAUDE.md
/ AGENTS.md): a shimmed crypto block must not be reported as integrated. Each
crypto block is reported REAL only when its harness elaborates clean per-run
from a filelist generated by scripts/gen_ot_flist.py.

With all 9 blocks real, three functional datapaths are proven through the real
e1_rot_xbar (tlul_adapter_host + tlul_socket_1n): (d) the HMAC register datapath
returns a FIPS 180-4 SHA-256 KAT (datapath_kat_hmac); (e) the EDN entropy
sideband stack (entropy_src -> csrng -> edn, e1_rot_ot_entropy_stack) delivers
masking entropy to the real KMAC, which returns a FIPS 202 SHA3-256 KAT
(entropy_stack_functional); and (f) the real OpenTitan keymgr advances its key
ladder Reset->Init->CreatorRootKey through the real KMAC KDF (with EDN-sourced
masking entropy) and emits a key that is bound to the creator SW binding input
(keymgr_ladder_functional, e1_rot_ot_keymgr_stack). Once the keymgr ladder is
proven, every buildable RTL/firmware item is closed and the gate stays BLOCKED
on a SINGLE remaining dependency that is PHYSICAL/SILICON
(rot_crypto_fips_entropy_physical): the entropy stack runs only in boot-time
BYPASS mode fed by a deterministic behavioral RNG (no real AST analog noise
source in simulation), so it carries NO FIPS / SP800-90B claim and no
provisioned silicon device identity exists. That is an analog/silicon blocker,
not a buildable gap. The keymgr KAT proves the hardware key-ladder DATAPATH and
input binding with DETERMINISTIC sim seeds -- NOT a provisioned silicon UDS.

If Verilator or cocotb is unavailable, or the OpenTitan checkout is absent, the
gate reports BLOCKED with the missing dependency and exits non-zero.
"""

from __future__ import annotations

import datetime as _dt
import json
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "build/reports/rot_integration.json"
OT_MANIFEST = ROOT / "external/opentitan/pin-manifest.json"
OT_CHECKOUT = ROOT / "external/opentitan/opentitan"
IBEX_FLIST = ROOT / "verify/cocotb/integration/ibex_pmc_min.f"
COCOTB_RESULTS = ROOT / "verify/cocotb/rot/results.xml"
KAT_RESULTS = ROOT / "verify/cocotb/rot/results_kat.xml"
KAT_MAKEFILE = "Makefile.kat"
KAT_TEST = "hmac_sha256_kat_through_xbar"
ENTROPY_KAT_RESULTS = ROOT / "verify/cocotb/rot/results_entropy_kat.xml"
ENTROPY_KAT_MAKEFILE = "Makefile.entropy_kat"
ENTROPY_KAT_TEST = "kmac_sha3_kat_edn_entropy"
KEYMGR_KAT_RESULTS = ROOT / "verify/cocotb/rot/results_keymgr_kat.xml"
KEYMGR_KAT_MAKEFILE = "Makefile.keymgr_kat"
KEYMGR_KAT_TEST = "keymgr_ladder_advance_and_bind"
GEN_FLIST = ROOT / "scripts/gen_ot_flist.py"
OT_BLOCKS_RTL = ROOT / "rtl/security/rot/e1_rot_ot_blocks.sv"
FLIST_DIR = ROOT / "build/rot_ot/flists"

# Upstream OpenTitan Verilator lint waivers. These are the warning classes
# OpenTitan itself waives in each block's hw/ip/<blk>/lint/<blk>.vlt; applying
# them lets the vendored RTL elaborate clean without modifying the read-only
# upstream tree. They are diagnostics-only (no functional masking).
OT_WAIVERS = [
    "-Wall",
    "-Wno-WIDTHEXPAND",
    "-Wno-WIDTHTRUNC",
    "-Wno-UNUSEDPARAM",
    "-Wno-UNUSEDSIGNAL",
    "-Wno-UNUSEDGENVAR",
    "-Wno-UNOPTFLAT",
    "-Wno-CASEINCOMPLETE",
    "-Wno-LATCH",
    "-Wno-PINMISSING",
    "-Wno-PINCONNECTEMPTY",
    "-Wno-DECLFILENAME",
    "-Wno-ASCRANGE",
    "-Wno-MULTIDRIVEN",
    "-Wno-CMPCONST",
    "-Wno-SYNCASYNCNET",
    "-Wno-TIMESCALEMOD",
    "-Wno-CONSTRAINTIGN",
    "-Wno-ALWCOMBORDER",
    "-Wno-SYMRSVDWORD",
]

# OpenTitan crypto/security blocks integrated for real. Each maps the inventory
# name to its FuseSoC VLNV (for gen_ot_flist.py), the e1_rot_ot_<harness> module
# that wraps the vendored IP, and the E1_ROT_INSTANTIATE_<DEFINE> that gates it
# into e1_rot_top. A block is reported REAL only if its harness elaborates clean
# under Verilator with the generated filelist (proven per-run, not asserted).
CRYPTO_BLOCKS = [
    {
        "name": "rom_ctrl",
        "vlnv": "lowrisc:ip:rom_ctrl",
        "harness": "e1_rot_ot_rom_ctrl",
        "define": "E1_ROT_INSTANTIATE_ROM_CTRL",
    },
    {
        "name": "keymgr",
        "vlnv": "lowrisc:ip:keymgr",
        "harness": "e1_rot_ot_keymgr",
        "define": "E1_ROT_INSTANTIATE_KEYMGR",
    },
    {
        "name": "kmac",
        "vlnv": "lowrisc:ip:kmac",
        "harness": "e1_rot_ot_kmac",
        "define": "E1_ROT_INSTANTIATE_KMAC",
    },
    {
        "name": "hmac",
        "vlnv": "lowrisc:ip:hmac",
        "harness": "e1_rot_ot_hmac",
        "define": "E1_ROT_INSTANTIATE_HMAC",
    },
    {
        "name": "aes",
        "vlnv": "lowrisc:ip:aes",
        "harness": "e1_rot_ot_aes",
        "define": "E1_ROT_INSTANTIATE_AES",
    },
    {
        "name": "csrng",
        "vlnv": "lowrisc:ip:csrng",
        "harness": "e1_rot_ot_csrng",
        "define": "E1_ROT_INSTANTIATE_CSRNG",
    },
    {
        "name": "edn",
        "vlnv": "lowrisc:ip:edn",
        "harness": "e1_rot_ot_edn",
        "define": "E1_ROT_INSTANTIATE_EDN",
    },
    {
        "name": "entropy_src",
        "vlnv": "lowrisc:ip:entropy_src",
        "harness": "e1_rot_ot_entropy_src",
        "define": "E1_ROT_INSTANTIATE_ENTROPY_SRC",
    },
    {
        "name": "alert_handler",
        "vlnv": "lowrisc:ip:alert_handler",
        "harness": "e1_rot_ot_alert_handler",
        "define": "E1_ROT_INSTANTIATE_ALERT_HANDLER",
    },
]

# Spine RTL (no Ibex) -- this is the scope that elaborates clean stand-alone.
SPINE_SOURCES = [
    "rtl/security/rot/e1_rot_tlul_pkg.sv",
    "rtl/security/otp/e1_otp_map.sv",
    "rtl/security/rot/e1_rot_crypto_shim.sv",
    "rtl/security/rot/e1_rot_mailbox.sv",
    "rtl/security/rot/e1_rot_reset_seq.sv",
    "rtl/security/rot/e1_rot_top.sv",
]

# Missing dependency reported for any crypto block whose real RTL fails to
# elaborate in the gate's flow (i.e. would fall back to the fail-closed shim).
MISSING_OT_DEP = (
    "OpenTitan block RTL did not elaborate clean under Verilator from the "
    "generated filelist (scripts/gen_ot_flist.py); falls back to the "
    "fail-closed e1_rot_crypto_shim"
)

# Spine blocks that are real by construction (E1-owned RTL or FuseSoC-staged
# Ibex), proven by the spine/Ibex elaborate checks and the cocotb contracts.
SPINE_BLOCKS = [
    {
        "name": "ibex_rv32imc",
        "detail": "lowRISC ibex_top from the FuseSoC-staged tree "
        "(external/ibex/ibex/build, shared with the PMC lane); "
        "elaborated under E1_ROT_INSTANTIATE_IBEX.",
    },
    {
        "name": "rot_sram_maskrom",
        "detail": "E1 behavioral RoT instruction/data SRAM + mask-ROM region in e1_rot_top.sv.",
    },
    {
        "name": "e1_otp_map",
        "detail": "W4 OTP controller (rtl/security/otp/e1_otp_map.sv), "
        "instantiated for real with 2-of-3 majority + parity fault.",
    },
    {
        "name": "e1_rot_mailbox",
        "detail": "AP<->RoT TL-UL mailbox; round-trip + AP-isolation proven by cocotb.",
    },
    {
        "name": "e1_rot_reset_seq",
        "detail": "Cold-boot reset sequencer; fail-closed reset-release proven by cocotb.",
    },
    {
        "name": "e1_lc_ctrl",
        "detail": "W5 lifecycle binding: the OTP lifecycle one-hot drives the "
        "reset-release SCRAP gating directly; the W5 controller binds by "
        "name under E1_ROT_HAVE_LC_CTRL when present.",
    },
]

EXPECTED_COCOTB_TESTS = (
    "rot_released_first_cores_held",
    "cores_released_on_verified_boot",
    "cores_stay_in_reset_when_not_verified",
    "scrap_latches_halt_and_never_releases",
    "mailbox_request_response_roundtrip",
    "ap_cannot_write_response_bank",
)

FALSE_CLAIM_FLAGS = {
    "secure_boot_claim_allowed": False,
    "hardware_key_claim_allowed": False,
    "attestation_claim_allowed": False,
    "fips_entropy_claim_allowed": False,
    "provisioned_identity_claim_allowed": False,
    "silicon_claim_allowed": False,
    "release_claim_allowed": False,
}


def structured_findings(
    *,
    checks: list[dict],
    shimmed: list[dict],
    blocker_id: str | None,
    blocker_reason: str | None,
    evidence_paths: list[str],
) -> list[dict]:
    findings: list[dict] = []
    for check in checks:
        if check.get("status") == "pass":
            continue
        check_id = str(check.get("id", "check"))
        findings.append(
            {
                "code": f"rot_integration_check_{check.get('status')}_{check_id}",
                "severity": "blocker" if check.get("status") == "blocked" else "error",
                "message": str(check.get("detail", "")),
                "evidence": check_id,
                "next_step": "Repair or rerun the named RoT integration subcheck.",
            }
        )
    for item in shimmed:
        block = str(item.get("block", "crypto_block"))
        findings.append(
            {
                "code": f"rot_integration_crypto_block_shimmed_{block}",
                "severity": "blocker",
                "message": str(item.get("missing_dependency", "crypto block remains shimmed")),
                "evidence": block,
                "next_step": "Elaborate the real OpenTitan block through its harness before claiming RoT integration.",
            }
        )
    if blocker_id:
        findings.append(
            {
                "code": f"rot_integration_blocker_{blocker_id}",
                "severity": "blocker",
                "message": blocker_reason or blocker_id,
                "evidence": evidence_paths,
                "next_step": "Close the named RoT blocker with real evidence before promoting security claims.",
            }
        )
    return findings


def _verilator() -> str | None:
    v = shutil.which("verilator")
    if v:
        return v
    oss = ROOT / "external/oss-cad-suite/bin/verilator"
    return str(oss) if oss.is_file() else None


def _now() -> str:
    return _dt.datetime.now(_dt.UTC).isoformat()


def check_pin() -> dict:
    """Resolve the OpenTitan pin manifest: checkout present and HEAD == pin."""
    if not OT_MANIFEST.is_file():
        return {
            "id": "opentitan_pin",
            "status": "blocked",
            "detail": f"manifest missing: {OT_MANIFEST.relative_to(ROOT)}",
        }
    manifest = json.loads(OT_MANIFEST.read_text())
    if manifest.get("license") != "Apache-2.0":
        return {
            "id": "opentitan_pin",
            "status": "fail",
            "detail": "OpenTitan license must be Apache-2.0",
        }
    if not OT_CHECKOUT.is_dir():
        return {
            "id": "opentitan_pin",
            "status": "blocked",
            "detail": "external/opentitan/opentitan absent; run scripts/bootstrap_opentitan.sh",
        }
    try:
        head = subprocess.check_output(
            ["git", "-C", str(OT_CHECKOUT), "rev-parse", "HEAD"], text=True, stderr=subprocess.PIPE
        ).strip()
    except subprocess.CalledProcessError as exc:
        return {
            "id": "opentitan_pin",
            "status": "blocked",
            "detail": f"rev-parse failed: {exc.stderr.strip()}",
        }
    pin = manifest.get("upstream_commit_pinned", "")
    if head != pin:
        return {
            "id": "opentitan_pin",
            "status": "fail",
            "detail": f"HEAD={head[:12]} != pin={pin[:12]}",
        }
    for rel in manifest.get("minimum_required_files", []):
        if not (ROOT / rel).is_file():
            return {
                "id": "opentitan_pin",
                "status": "blocked",
                "detail": f"missing required file {rel}",
            }
    return {
        "id": "opentitan_pin",
        "status": "pass",
        "detail": f"HEAD={head[:12]} matches pin ({manifest['upstream_tag_pinned']})",
    }


def _lint(verilator: str, sources: list[str], extra: list[str]) -> tuple[bool, str]:
    cmd = [
        verilator,
        "--lint-only",
        "-Wall",
        "-Wno-DECLFILENAME",
        "-Wno-UNUSEDPARAM",
        *extra,
        *[str(ROOT / s) for s in sources],
        "--top-module",
        "e1_rot_top",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    warns = [ln for ln in proc.stderr.splitlines() if "%Warning" in ln or "%Error" in ln]
    return (proc.returncode == 0 and not warns), "\n".join(warns[:8])


def check_elaborate_spine(verilator: str) -> dict:
    ok, msg = _lint(verilator, SPINE_SOURCES, [])
    if ok:
        return {
            "id": "elaborate_spine",
            "status": "pass",
            "detail": "e1_rot_top spine (Ibex undefined) lints clean",
        }
    return {"id": "elaborate_spine", "status": "fail", "detail": f"spine lint failed: {msg}"}


def check_elaborate_ibex(verilator: str) -> dict:
    if not IBEX_FLIST.is_file():
        return {
            "id": "elaborate_ibex",
            "status": "blocked",
            "detail": f"{IBEX_FLIST.relative_to(ROOT)} missing; run scripts/bootstrap_ibex.sh",
        }
    incdirs, ibex_src = [], []
    for line in IBEX_FLIST.read_text().splitlines():
        line = line.strip()
        if line.startswith("+incdir+"):
            incdirs.append("+incdir+" + str(ROOT / line[len("+incdir+") :]))
        elif line and not line.startswith(("#", "+")):
            ibex_src.append(str(ROOT / line))
    missing = [p for p in ibex_src if not Path(p).is_file()]
    if missing:
        return {
            "id": "elaborate_ibex",
            "status": "blocked",
            "detail": f"{len(missing)} staged Ibex source(s) absent; run "
            "scripts/bootstrap_ibex.sh (e.g. {})".format(Path(missing[0]).name),
        }
    waivers = [
        "-Wno-PINMISSING",
        "-Wno-WIDTHTRUNC",
        "-Wno-WIDTHEXPAND",
        "-Wno-CASEINCOMPLETE",
        "-Wno-LATCH",
        "-Wno-ASCRANGE",
        "-Wno-MULTIDRIVEN",
        "-Wno-CMPCONST",
        "-Wno-UNUSEDGENVAR",
        "-Wno-CONSTRAINTIGN",
        "-Wno-UNUSEDSIGNAL",
        "-Wno-UNOPTFLAT",
        "-Wno-SYNCASYNCNET",
        "-Wno-PINCONNECTEMPTY",
        "-Wno-TIMESCALEMOD",
        "+define+E1_ROT_INSTANTIATE_IBEX",
        "+define+SYNTHESIS",
        *incdirs,
    ]
    cmd = [
        verilator,
        "--lint-only",
        "-Wno-fatal",
        "-Wall",
        *waivers,
        *ibex_src,
        *[str(ROOT / s) for s in SPINE_SOURCES],
        "--top-module",
        "e1_rot_top",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    bad = [ln for ln in proc.stderr.splitlines() if "%Error" in ln]
    if proc.returncode == 0 and not bad:
        return {
            "id": "elaborate_ibex",
            "status": "pass",
            "detail": f"e1_rot_top + real Ibex ({len(ibex_src)} src) "
            "elaborates clean (upstream lint waivers applied)",
        }
    return {
        "id": "elaborate_ibex",
        "status": "fail",
        "detail": "Ibex-build elaboration failed: " + "\n".join(bad[:6]),
    }


def _gen_block_flist(vlnv: str) -> tuple[Path | None, str]:
    """Generate a block's Verilator filelist via scripts/gen_ot_flist.py."""
    proc = subprocess.run(
        [sys.executable, str(GEN_FLIST), vlnv], capture_output=True, text=True, cwd=ROOT
    )
    name = vlnv.split(":")[2]
    flist = FLIST_DIR / f"{name}.f"
    if proc.returncode != 0 or not flist.is_file():
        return None, (proc.stderr.strip() or proc.stdout.strip())[:200]
    return flist, ""


def _lint_block(verilator: str, flist: Path, top: str, extra_src: list[str]) -> tuple[bool, str]:
    cmd = [
        verilator,
        "--lint-only",
        "-Wno-fatal",
        *OT_WAIVERS,
        "-sv",
        "-f",
        str(flist),
        *extra_src,
        "--top-module",
        top,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    diags = [ln for ln in proc.stderr.splitlines() if "%Error" in ln or "%Warning" in ln]
    return (proc.returncode == 0 and not diags), "\n".join(diags[:6])


def check_elaborate_crypto(verilator: str) -> tuple[list[dict], dict]:
    """Elaborate each OpenTitan crypto block's real RTL via its harness.

    Returns (per_block_status, integrated_top_check). A block is REAL iff its
    e1_rot_ot_<harness> wrapper (real vendored IP + sideband tie-offs, TL device
    port exposed) lints clean from the generated filelist. The integrated check
    additionally elaborates e1_rot_top with every passing block's
    E1_ROT_INSTANTIATE_<DEFINE> set.
    """
    if not OT_BLOCKS_RTL.is_file():
        miss = {
            "id": "elaborate_crypto_integrated",
            "status": "blocked",
            "detail": f"{OT_BLOCKS_RTL.relative_to(ROOT)} missing",
        }
        return (
            [{"name": b["name"], "real": False, "missing": MISSING_OT_DEP} for b in CRYPTO_BLOCKS],
            miss,
        )

    FLIST_DIR.mkdir(parents=True, exist_ok=True)
    per_block: list[dict] = []
    real_defines: list[str] = []
    for blk in CRYPTO_BLOCKS:
        flist, err = _gen_block_flist(blk["vlnv"])
        if flist is None:
            per_block.append(
                {
                    "name": blk["name"],
                    "real": False,
                    "missing": f"filelist generation failed: {err}",
                }
            )
            continue
        ok, msg = _lint_block(verilator, flist, blk["harness"], [str(OT_BLOCKS_RTL)])
        if ok:
            per_block.append(
                {
                    "name": blk["name"],
                    "real": True,
                    "detail": f"vendored OpenTitan {blk['name']} elaborates clean "
                    f"via {blk['harness']} (def {blk['define']}); "
                    "filelist scripts/gen_ot_flist.py "
                    f"{blk['vlnv']}",
                }
            )
            real_defines.append(blk["define"])
        else:
            per_block.append(
                {"name": blk["name"], "real": False, "missing": f"{MISSING_OT_DEP}: {msg}"}
            )

    # Integrated check: e1_rot_top with all real blocks instantiated, against the
    # union of every real block's filelist (deduped).
    integrated = _integrated_top_check(verilator, real_defines)
    return per_block, integrated


def _integrated_top_check(verilator: str, defines: list[str]) -> dict:
    if not defines:
        return {
            "id": "elaborate_crypto_integrated",
            "status": "fail",
            "detail": "no crypto block elaborated; e1_rot_top would be all-shim",
        }
    incdirs: list[str] = []
    srcs: list[str] = []
    for blk in CRYPTO_BLOCKS:
        if blk["define"] not in defines:
            continue
        flist = FLIST_DIR / f"{blk['name']}.f"
        for ln in flist.read_text().splitlines():
            ln = ln.strip()
            if not ln:
                continue
            (incdirs if ln.startswith("+incdir+") else srcs).append(ln)
    incdirs = list(dict.fromkeys(incdirs))
    srcs = list(dict.fromkeys(srcs))
    # The crossbar (e1_rot_xbar) wires the now-real block TL device ports into a
    # single Ibex-style host via the vendored tlul_adapter_host + tlul_socket_1n.
    # tlul_adapter_host is the only TL-UL fabric file no block closure pulls in
    # on its own; tlul_socket_1n already comes in via the block flists.
    adapter_host = str(ROOT / "external/opentitan/opentitan/hw/ip/tlul/rtl/tlul_adapter_host.sv")
    cmd = [
        verilator,
        "--lint-only",
        "-Wno-fatal",
        *OT_WAIVERS,
        *[f"+define+{d}" for d in defines],
        "-sv",
        *incdirs,
        *srcs,
        adapter_host,
        str(ROOT / "rtl/security/rot/e1_rot_xbar.sv"),
        str(OT_BLOCKS_RTL),
        *[str(ROOT / s) for s in SPINE_SOURCES],
        "--top-module",
        "e1_rot_top",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=ROOT)
    bad = [ln for ln in proc.stderr.splitlines() if "%Error" in ln]
    if proc.returncode == 0 and not bad:
        return {
            "id": "elaborate_crypto_integrated",
            "status": "pass",
            "detail": f"e1_rot_top + {len(defines)} real OpenTitan crypto "
            f"block(s) ({len(srcs)} OT src) elaborates clean "
            "(upstream waivers applied)",
        }
    return {
        "id": "elaborate_crypto_integrated",
        "status": "fail",
        "detail": "integrated e1_rot_top elaboration failed: " + "\n".join(bad[:6]),
    }


def check_cocotb() -> dict:
    rc = subprocess.run(
        ["make", "-C", str(ROOT / "verify/cocotb/rot")], capture_output=True, text=True, cwd=ROOT
    )
    if not COCOTB_RESULTS.is_file():
        return {
            "id": "cocotb_reset_release_mailbox",
            "status": "blocked",
            "detail": "no results.xml; cocotb/verilator unavailable. " + rc.stderr.splitlines()[-1]
            if rc.stderr
            else "",
        }
    tree = ET.parse(COCOTB_RESULTS)
    seen, failed = set(), []
    for tc in tree.iter("testcase"):
        name = tc.get("name", "")
        seen.add(name)
        if tc.find("failure") is not None or tc.find("error") is not None:
            failed.append(name)
    missing = [t for t in EXPECTED_COCOTB_TESTS if t not in seen]
    if failed or missing:
        return {
            "id": "cocotb_reset_release_mailbox",
            "status": "fail",
            "detail": f"failed={failed} missing={missing}",
        }
    return {
        "id": "cocotb_reset_release_mailbox",
        "status": "pass",
        "detail": f"{len(EXPECTED_COCOTB_TESTS)} reset-release + mailbox tests passed",
    }


def check_datapath_kat() -> dict:
    """Functional crypto-datapath KAT: SHA-256("abc") through the real crossbar.

    Builds e1_rot_xbar (tlul_adapter_host + tlul_socket_1n) with the real
    OpenTitan HMAC block on a device window and drives the crossbar host port
    from cocotb, exactly as the RoT Ibex data port would. The test asserts the
    digest equals the FIPS 180-4 known answer; only the real hmac/sha2 RTL,
    reached through the real TL-UL fabric with command/response integrity, can
    produce it. This is the functional crypto result that advances the gate past
    rot_crypto_datapath_unwired for the HMAC datapath.
    """
    rc = subprocess.run(
        ["make", "-C", str(ROOT / "verify/cocotb/rot"), "-f", KAT_MAKEFILE],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if not KAT_RESULTS.is_file():
        last = rc.stderr.splitlines()[-1] if rc.stderr else ""
        return {
            "id": "datapath_kat_hmac",
            "status": "blocked",
            "detail": f"no results_kat.xml; cocotb/verilator unavailable. {last}",
        }
    tree = ET.parse(KAT_RESULTS)
    seen, failed = set(), []
    for tc in tree.iter("testcase"):
        name = tc.get("name", "")
        seen.add(name)
        if tc.find("failure") is not None or tc.find("error") is not None:
            failed.append(name)
    if KAT_TEST not in seen:
        return {
            "id": "datapath_kat_hmac",
            "status": "fail",
            "detail": f"KAT {KAT_TEST} did not run (seen={sorted(seen)})",
        }
    if failed:
        return {
            "id": "datapath_kat_hmac",
            "status": "fail",
            "detail": f"KAT failed: {failed}",
        }
    return {
        "id": "datapath_kat_hmac",
        "status": "pass",
        "detail": 'real OpenTitan HMAC computed SHA-256("abc") = '
        "ba7816bf...f20015ad (FIPS 180-4 KAT) through e1_rot_xbar "
        "(tlul_adapter_host -> tlul_socket_1n -> hmac); host->datapath->block "
        "proven functional",
    }


def check_entropy_kat() -> dict:
    """Functional entropy-stack KAT: SHA3-256("") by real KMAC, EDN-sourced.

    Builds the real entropy interconnect (e1_rot_ot_entropy_stack: entropy_src ->
    csrng -> edn -> aes/kmac/keymgr, fed by the behavioral RNG noise model) on the
    crossbar device windows and drives the crossbar host port from cocotb to bring
    up the stack (entropy_src boot-bypass, csrng enable, edn boot-request mode),
    then programs the real KMAC for a plain SHA3-256 hash with EnMasking=1 and
    CFG.entropy_mode = EdnMode. KMAC cannot complete a masked hash without entropy;
    with EdnMode that entropy can only come from the real entropy_src -> csrng ->
    edn datapath. The test asserts the unmasked digest (XOR of the two state
    shares) equals the FIPS 202 known answer, proving the entropy stack delivers
    entropy to a consumer.

    ENTROPY MODE: boot-time BYPASS (FIPS conditioner bypassed) fed by a
    DETERMINISTIC behavioral RNG model. This proves the digital datapath in
    simulation; it is NOT a FIPS / SP800-90B entropy claim.
    """
    rc = subprocess.run(
        ["make", "-C", str(ROOT / "verify/cocotb/rot"), "-f", ENTROPY_KAT_MAKEFILE],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if not ENTROPY_KAT_RESULTS.is_file():
        last = rc.stderr.splitlines()[-1] if rc.stderr else ""
        return {
            "id": "entropy_stack_functional",
            "status": "blocked",
            "detail": f"no results_entropy_kat.xml; cocotb/verilator unavailable. {last}",
        }
    tree = ET.parse(ENTROPY_KAT_RESULTS)
    seen, failed = set(), []
    for tc in tree.iter("testcase"):
        name = tc.get("name", "")
        seen.add(name)
        if tc.find("failure") is not None or tc.find("error") is not None:
            failed.append(name)
    if ENTROPY_KAT_TEST not in seen:
        return {
            "id": "entropy_stack_functional",
            "status": "fail",
            "detail": f"KAT {ENTROPY_KAT_TEST} did not run (seen={sorted(seen)})",
        }
    if failed:
        return {
            "id": "entropy_stack_functional",
            "status": "fail",
            "detail": f"entropy KAT failed: {failed}",
        }
    return {
        "id": "entropy_stack_functional",
        "status": "pass",
        "detail": "real OpenTitan entropy_src -> csrng -> edn delivered masking "
        'entropy to KMAC, which computed SHA3-256("") = '
        "f8c6ffa7...4a43f880 (FIPS 202 KAT) through e1_rot_xbar; entropy stack "
        "proven functional in BOOT-BYPASS mode (deterministic behavioral RNG, "
        "NOT a FIPS/SP800-90B entropy claim)",
    }


def check_keymgr_kat() -> dict:
    """Functional keymgr key-ladder KAT: Reset->Init->CreatorRootKey + bound key.

    Builds the real keymgr key-ladder stack (e1_rot_ot_keymgr_stack: entropy_src
    -> csrng -> edn -> kmac + keymgr, with the keymgr KMAC-KDF app port wired to
    the real KMAC and the keymgr sideload key fed back as the KDF stage key) on
    the crossbar device windows and drives the crossbar host port from cocotb to
    bring up entropy, then sequences the real OpenTitan keymgr CSRs through
    Advance (Reset->Init), Advance (Init->CreatorRootKey, a KMAC KDF of the
    creator stage), generate-HW-output to the KMAC sideload destination, and
    generate-SW-output. The test asserts the ladder reaches WORKING_STATE ==
    CreatorRootKey with OP_STATUS == DONE_SUCCESS and ERR_CODE == 0 on every
    step, and that BOTH the SW-output key and the hardware sideload key diverge
    when the run is repeated with a different creator SW binding -- proving the
    binding input flows through the real KMAC KDF into the derived key.

    HONESTY CAVEAT: the creator/owner roots are FIXED deterministic simulation
    constants (otp_key_i = OTP_KEYMGR_KEY_DEFAULT, a fixed otp_device_id, the
    keymgr_pkg RndCnst identity seeds) and the entropy is the deterministic
    boot-bypass behavioral RNG. This proves the hardware key-ladder DATAPATH and
    input binding; it is NOT a provisioned silicon device identity (no real UDS /
    fused secret / silicon entropy). The derived key is not recomputed in Python
    (the full AdvDataWidth KDF blob mixes vendored RndCnst seeds + device id +
    health state); the proof is self-consistent ladder advance plus deterministic
    input-binding divergence.
    """
    rc = subprocess.run(
        ["make", "-C", str(ROOT / "verify/cocotb/rot"), "-f", KEYMGR_KAT_MAKEFILE],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if not KEYMGR_KAT_RESULTS.is_file():
        last = rc.stderr.splitlines()[-1] if rc.stderr else ""
        return {
            "id": "keymgr_ladder_functional",
            "status": "blocked",
            "detail": f"no results_keymgr_kat.xml; cocotb/verilator unavailable. {last}",
        }
    tree = ET.parse(KEYMGR_KAT_RESULTS)
    seen, failed = set(), []
    for tc in tree.iter("testcase"):
        name = tc.get("name", "")
        seen.add(name)
        if tc.find("failure") is not None or tc.find("error") is not None:
            failed.append(name)
    if KEYMGR_KAT_TEST not in seen:
        return {
            "id": "keymgr_ladder_functional",
            "status": "fail",
            "detail": f"KAT {KEYMGR_KAT_TEST} did not run (seen={sorted(seen)})",
        }
    if failed:
        return {
            "id": "keymgr_ladder_functional",
            "status": "fail",
            "detail": f"keymgr KAT failed: {failed}",
        }
    return {
        "id": "keymgr_ladder_functional",
        "status": "pass",
        "detail": "real OpenTitan keymgr advanced Reset->Init->CreatorRootKey "
        "(DONE_SUCCESS, ERR_CODE=0) KDFing each stage through the real KMAC with "
        "EDN-sourced masking entropy; generate-SW-output and generate-HW-output "
        "(KMAC sideload) produced a key that diverges with the creator SW binding "
        "input (tamper divergence). Proves the hardware key-ladder DATAPATH + "
        "input binding; deterministic SIM seeds, NOT a provisioned silicon UDS / "
        "device identity",
    }


# The HMAC crypto datapath is wired and proven functional (datapath_kat_hmac);
# the EDN entropy sideband stack is now ALSO wired and proven functional
# (entropy_stack_functional): entropy_src -> csrng -> edn delivers masking
# entropy to KMAC, which returns a verified SHA3-256 KAT. MISSING_DATAPATH is
# the fallback named blocker used only if the HMAC datapath itself regresses
# (all blocks real but datapath_kat_hmac not proven).
MISSING_DATAPATH = (
    "The TL-UL register datapath through e1_rot_xbar (tlul_adapter_host + "
    "tlul_socket_1n) did not return a verified functional crypto result, so no "
    "secure-boot / hardware-key / attestation claim is permitted."
)

# Named remainder once BOTH the HMAC datapath and the entropy stack are proven
# functional. Two real, precise items keep the gate fail-closed:
#   (1) the entropy stack ran in boot-time BYPASS mode fed by a deterministic
#       behavioral RNG -- a valid simulation bring-up but NOT a production FIPS /
#       SP800-90B entropy claim (real AST noise source + FIPS health-test windows
#       + KMAC conditioner in FIPS mode remain to be exercised);
#   (2) the keymgr sideload key ladder is wired structurally (keymgr is an EDN
#       endpoint in e1_rot_ot_entropy_stack) but no key-ladder advance / sideload
#       key read is exercised end to end, so no hardware-key / DICE / attestation
#       claim is permitted.
MISSING_FIPS_AND_SIDELOAD = (
    "Two precise items keep the RoT crypto subsystem fail-closed: "
    "(1) FIPS entropy -- the entropy stack is proven functional only in "
    "boot-time BYPASS mode fed by a DETERMINISTIC behavioral RNG (no FIPS / "
    "SP800-90B entropy guarantee); production FIPS bring-up (real AST noise "
    "source, full health-test windows, KMAC conditioner in FIPS mode) is the "
    "remaining entropy step. (2) keymgr sideload key ladder -- keymgr is wired "
    "as a real EDN endpoint but no key-ladder advance / sideload key read is "
    "exercised, so no hardware-key / DICE / attestation claim is permitted."
)

# Named remainder once the keymgr key-ladder KAT ALSO passes
# (keymgr_ladder_functional): the only functional/buildable items are closed.
# The single remaining blocker is PHYSICAL: the entropy stack runs in boot-time
# BYPASS mode fed by a deterministic behavioral RNG because there is no real AST
# analog noise source in simulation. This is an analog/silicon dependency, NOT a
# buildable RTL/firmware gap -- it cannot be closed without silicon (or an AST
# behavioral+characterization model that is out of scope here). The keymgr KAT
# proves the hardware key-ladder DATAPATH and input binding with deterministic
# sim seeds, which is NOT a provisioned silicon UDS / device identity; that
# provisioning is downstream of having real silicon entropy and is part of the
# same physical dependency.
MISSING_FIPS_ENTROPY_PHYSICAL = (
    "The ONLY remaining RoT crypto blocker is PHYSICAL/SILICON, not a buildable "
    "gap: FIPS entropy. The entropy stack is proven functional end to end "
    "(entropy_src -> csrng -> edn -> kmac/keymgr) but only in boot-time BYPASS "
    "mode fed by a DETERMINISTIC behavioral RNG (e1_rot_rng_model), because "
    "there is no real AST analog noise source in simulation -- so it carries NO "
    "FIPS / SP800-90B entropy guarantee. Closing it requires the real silicon "
    "AST noise source plus full health-test windows and the KMAC conditioner in "
    "FIPS mode; that is an analog/silicon dependency that cannot be exercised "
    "from RTL simulation. Consequently the keymgr key-ladder KAT proves the "
    "hardware key-ladder DATAPATH and input binding with DETERMINISTIC sim seeds "
    "(NOT a provisioned silicon UDS / device identity); real device-identity "
    "provisioning is downstream of having real silicon entropy and is part of "
    "the same physical dependency."
)


def main() -> int:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    checks = [check_pin()]

    verilator = _verilator()
    crypto_blocks: list[dict] = []
    if verilator is None:
        checks.append(
            {
                "id": "elaborate_spine",
                "status": "blocked",
                "detail": "verilator not found; install oss-cad-suite",
            }
        )
        checks.append(
            {"id": "elaborate_ibex", "status": "blocked", "detail": "verilator not found"}
        )
        checks.append(
            {
                "id": "elaborate_crypto_integrated",
                "status": "blocked",
                "detail": "verilator not found",
            }
        )
        crypto_blocks = [
            {"name": b["name"], "real": False, "missing": "verilator not found"}
            for b in CRYPTO_BLOCKS
        ]
    else:
        checks.append(check_elaborate_spine(verilator))
        checks.append(check_elaborate_ibex(verilator))
        crypto_blocks, integrated = check_elaborate_crypto(verilator)
        checks.append(integrated)
    checks.append(check_cocotb())

    real_blocks = [b["name"] for b in SPINE_BLOCKS]
    real_blocks += [b["name"] for b in crypto_blocks if b["real"]]
    shimmed = [
        {"block": b["name"], "missing_dependency": b["missing"]}
        for b in crypto_blocks
        if not b["real"]
    ]
    all_crypto_real = bool(crypto_blocks) and not shimmed

    # Functional crypto-datapath KAT only runs once the crossbar can be wired
    # (HMAC is real and the integrated top elaborates with it). If HMAC is
    # shimmed the datapath cannot be proven, so the KAT is not run and the gate
    # stays BLOCKED on the shimmed block above.
    hmac_real = any(b["name"] == "hmac" and b["real"] for b in crypto_blocks)
    integrated_ok = any(
        c["id"] == "elaborate_crypto_integrated" and c["status"] == "pass" for c in checks
    )
    kat = None
    entropy_kat = None
    keymgr_kat = None
    if verilator is not None and hmac_real and integrated_ok:
        kat = check_datapath_kat()
        checks.append(kat)
        # The entropy-stack KAT only runs once the HMAC datapath KAT proves the
        # crossbar is live; it brings up the real entropy_src -> csrng -> edn
        # stack and drives KMAC to a SHA3 KAT with EDN-sourced masking entropy.
        if kat["status"] == "pass":
            entropy_kat = check_entropy_kat()
            checks.append(entropy_kat)
            # The keymgr key-ladder KAT only runs once the entropy stack is
            # proven live; it advances the real keymgr Reset->Init->CreatorRootKey
            # through the real KMAC KDF and proves the derived key is input-bound.
            if entropy_kat["status"] == "pass":
                keymgr_kat = check_keymgr_kat()
                checks.append(keymgr_kat)
    kat_pass = kat is not None and kat["status"] == "pass"
    entropy_kat_pass = entropy_kat is not None and entropy_kat["status"] == "pass"
    keymgr_kat_pass = keymgr_kat is not None and keymgr_kat["status"] == "pass"

    # Gate verdict. Fail-closed law:
    #   * any FAIL check -> FAIL.
    #   * any BLOCKED check (missing tool/checkout) -> BLOCKED.
    #   * any shimmed crypto block -> BLOCKED (named missing elaboration dep).
    #   * all crypto blocks elaborate real, but TL/sideband data path not wired
    #     -> still BLOCKED on rot_crypto_datapath_unwired. The blocks are REAL
    #     RTL (15 real / 0 shim) but produce no functional crypto result yet;
    #     no secure-boot/key/attestation claim is permitted.
    has_fail = any(c["status"] == "fail" for c in checks)
    has_block = any(c["status"] == "blocked" for c in checks)

    if has_fail:
        status, blocker_id, blocker_reason = (
            "FAIL",
            "rot_check_failure",
            "; ".join(f"{c['id']}: {c['detail']}" for c in checks if c["status"] == "fail"),
        )
    elif has_block:
        status, blocker_id = "BLOCKED", "rot_dependency_missing"
        blocker_reason = "; ".join(
            f"{c['id']}: {c['detail']}" for c in checks if c["status"] == "blocked"
        )
    elif shimmed:
        status, blocker_id = "BLOCKED", "rot_crypto_blocks_shimmed"
        blocker_reason = (
            "Integration spine (Ibex + OTP + lifecycle + mailbox + reset "
            "sequencer) is REAL and elaborates/tests clean, but the following "
            "OpenTitan crypto/security blocks are fail-closed SHIMS, not "
            "integrated: "
            + ", ".join(s["block"] for s in shimmed)
            + ". Missing dependency: "
            + MISSING_OT_DEP
        )
    elif all_crypto_real and kat_pass and entropy_kat_pass and keymgr_kat_pass:
        # All three functional datapaths are proven: the HMAC register datapath
        # (datapath_kat_hmac), the EDN entropy sideband stack
        # (entropy_stack_functional), and the keymgr key-ladder
        # (keymgr_ladder_functional -- real keymgr advances
        # Reset->Init->CreatorRootKey through the real KMAC KDF and emits an
        # input-bound key). Every buildable RTL/firmware item is closed; the gate
        # stays BLOCKED on a SINGLE remaining dependency that is PHYSICAL/SILICON:
        # FIPS entropy (real AST analog noise source). Fail-closed: no production
        # FIPS-entropy / provisioned-silicon-identity claim is permitted, but
        # this is an analog/silicon blocker, not a buildable gap.
        status, blocker_id = "BLOCKED", "rot_crypto_fips_entropy_physical"
        blocker_reason = (
            "RoT TL-UL crypto datapath is WIRED and FUNCTIONAL end to end: the "
            "HMAC register datapath returns a FIPS 180-4 SHA-256 KAT "
            "(datapath_kat_hmac); the EDN entropy stack (entropy_src -> csrng -> "
            "edn) delivers masking entropy to KMAC, which returns a FIPS 202 "
            "SHA3-256 KAT (entropy_stack_functional); AND the real OpenTitan "
            "keymgr advances its key ladder Reset->Init->CreatorRootKey through "
            "the real KMAC KDF and emits an input-bound key "
            "(keymgr_ladder_functional). Remaining named blocker: " + MISSING_FIPS_ENTROPY_PHYSICAL
        )
    elif all_crypto_real and kat_pass and entropy_kat_pass:
        # The HMAC datapath and the EDN entropy stack are proven, but the keymgr
        # key-ladder KAT is not (did not pass or did not run). The gate stays
        # BLOCKED on the PRECISE remainder: bypass-mode entropy is not a FIPS
        # claim, and the keymgr key ladder is not yet exercised end to end.
        status, blocker_id = "BLOCKED", "rot_crypto_fips_and_sideload"
        km_detail = keymgr_kat["detail"] if keymgr_kat is not None else "keymgr KAT not run"
        blocker_reason = (
            "RoT TL-UL crypto datapath is WIRED and FUNCTIONAL: the HMAC "
            "register datapath returns a FIPS 180-4 SHA-256 KAT "
            "(datapath_kat_hmac) AND the EDN entropy stack (entropy_src -> csrng "
            "-> edn) delivers masking entropy to KMAC, which returns a FIPS 202 "
            "SHA3-256 KAT (entropy_stack_functional). keymgr key-ladder KAT not "
            f"proven (keymgr_ladder_functional: {km_detail}). Remaining named "
            "blocker: " + MISSING_FIPS_AND_SIDELOAD
        )
    elif all_crypto_real and kat_pass:
        # The HMAC datapath is proven functional but the entropy stack KAT is not
        # (did not pass or did not run) -> still BLOCKED on the NAMED entropy
        # sideband. Fail-closed: blocks that need the entropy stack produce no
        # functional result.
        status, blocker_id = "BLOCKED", "rot_crypto_sideband_unwired"
        ek_detail = entropy_kat["detail"] if entropy_kat is not None else "entropy KAT not run"
        blocker_reason = (
            "RoT TL-UL crypto datapath is WIRED and FUNCTIONAL for HMAC: the "
            "Ibex-style host port reaches the real OpenTitan hmac through "
            "e1_rot_xbar and a FIPS 180-4 SHA-256 KAT is verified end to end "
            "(datapath_kat_hmac). The EDN entropy sideband stack is wired "
            "(e1_rot_ot_entropy_stack: entropy_src -> csrng -> edn -> "
            "aes/kmac/keymgr) but not proven functional "
            f"(entropy_stack_functional: {ek_detail}). No secure-boot / "
            "hardware-key / attestation claim is permitted for blocks that "
            "depend on the entropy stack."
        )
    elif all_crypto_real and not kat_pass:
        # Blocks are real and the integrated top elaborates, but the functional
        # datapath KAT did not pass (or did not run) -> still BLOCKED on the
        # datapath, fail-closed: no functional crypto result is proven.
        status, blocker_id = "BLOCKED", "rot_crypto_datapath_unwired"
        kat_detail = kat["detail"] if kat is not None else "KAT not run"
        blocker_reason = (
            "All 9 OpenTitan crypto/security blocks elaborate as REAL RTL, but "
            "no functional crypto result is proven through the datapath "
            f"(datapath_kat_hmac: {kat_detail}). Missing dependency: " + MISSING_DATAPATH
        )
    else:
        status, blocker_id, blocker_reason = "PASS", None, None

    if all_crypto_real and kat_pass and entropy_kat_pass and keymgr_kat_pass:
        boundary_crypto = (
            "All 9 OpenTitan crypto/security blocks (rom_ctrl/keymgr/kmac/hmac/"
            "aes/csrng/edn/entropy_src/alert_handler) elaborate as REAL vendored "
            "RTL in e1_rot_top and their TL-UL register ports are WIRED into the "
            "Ibex-style host through e1_rot_xbar (vendored tlul_adapter_host + "
            "tlul_socket_1n). THREE functional datapaths are PROVEN: (a) the HMAC "
            'datapath -- a FIPS 180-4 SHA-256("abc") KAT computed by the real '
            "hmac block and read back through the crossbar (datapath_kat_hmac); "
            "(b) the EDN entropy sideband stack -- the real entropy_src -> csrng "
            "-> edn chain delivers masking entropy to the real KMAC, which "
            'computes a FIPS 202 SHA3-256("") KAT (entropy_stack_functional); '
            "(c) the keymgr key ladder -- the real OpenTitan keymgr advances "
            "Reset->Init->CreatorRootKey (DONE_SUCCESS, ERR_CODE=0) KDFing each "
            "stage through the real KMAC with EDN-sourced masking entropy, and "
            "generate-SW-output / generate-HW-output (KMAC sideload) produce a key "
            "that diverges with the creator SW binding input "
            "(keymgr_ladder_functional). The keymgr KAT proves the hardware "
            "key-ladder DATAPATH and input binding with DETERMINISTIC sim seeds; "
            "it is NOT a provisioned silicon UDS / device identity. The entropy "
            "stack ran in BOOT-BYPASS mode fed by a DETERMINISTIC behavioral RNG, "
            "so the ONLY remaining blocker is PHYSICAL/SILICON: FIPS entropy (real "
            "AST analog noise source). NO production FIPS-entropy / "
            "provisioned-identity claim is permitted until silicon entropy lands; "
            "that is an analog/silicon dependency, not a buildable gap."
        )
    elif all_crypto_real and kat_pass and entropy_kat_pass:
        boundary_crypto = (
            "All 9 OpenTitan crypto/security blocks elaborate as REAL vendored "
            "RTL in e1_rot_top and are wired into e1_rot_xbar. The HMAC datapath "
            "(datapath_kat_hmac) and the EDN entropy stack "
            "(entropy_stack_functional) are PROVEN FUNCTIONAL. The keymgr "
            "key-ladder KAT (keymgr_ladder_functional) is not yet proven, and the "
            "entropy stack ran in BOOT-BYPASS mode (deterministic behavioral RNG, "
            "NOT a FIPS claim). NO production FIPS-entropy / hardware-key / DICE / "
            "attestation claim is permitted until those remaining steps land."
        )
    elif all_crypto_real and kat_pass:
        boundary_crypto = (
            "All 9 OpenTitan crypto/security blocks elaborate as REAL vendored "
            "RTL in e1_rot_top and are wired into e1_rot_xbar. The HMAC datapath "
            "is PROVEN FUNCTIONAL (datapath_kat_hmac), and the EDN entropy stack "
            "is WIRED (e1_rot_ot_entropy_stack: entropy_src -> csrng -> edn -> "
            "aes/kmac/keymgr) but not proven functional. NO secure-boot / "
            "hardware-key / attestation claim is permitted for blocks that depend "
            "on the entropy stack."
        )
    elif all_crypto_real:
        boundary_crypto = (
            "All 9 OpenTitan crypto/security blocks elaborate as REAL vendored "
            "RTL in e1_rot_top and are wired into e1_rot_xbar, but the functional "
            "datapath KAT is not proven: NO functional crypto or secure-boot "
            "result is claimed. No secure-boot / hardware-key / attestation "
            "claim is permitted from this tree."
        )
    else:
        boundary_crypto = (
            "The OpenTitan crypto/security blocks that remain shimmed are bound "
            "via fail-closed E1 integration shims, NOT integrated -- reported "
            "BLOCKED with the named missing dependency. No secure-boot / "
            "hardware-key / attestation claim is permitted from this tree."
        )

    evidence_paths: list[str] = [
        "rtl/security/rot/e1_rot_top.sv",
        "rtl/security/rot/e1_rot_ot_blocks.sv",
        "rtl/security/rot/e1_rot_ot_entropy_stack.sv",
        "rtl/security/rot/e1_rot_ot_keymgr_stack.sv",
        "rtl/security/rot/e1_rot_xbar.sv",
        "rtl/security/rot/e1_rot_mailbox.sv",
        "rtl/security/rot/e1_rot_reset_seq.sv",
        "rtl/security/rot/e1_rot_crypto_shim.sv",
        "rtl/security/rot/e1_rot_tlul_pkg.sv",
        "scripts/gen_ot_flist.py",
        "verify/cocotb/test_e1_rot_top.py",
        "verify/cocotb/rot/e1_rot_top_tb.sv",
        "verify/cocotb/rot/e1_rot_kat_tb.sv",
        "verify/cocotb/rot/test_e1_rot_kat.py",
        "verify/cocotb/rot/Makefile.kat",
        "verify/cocotb/rot/e1_rot_entropy_kat_tb.sv",
        "verify/cocotb/rot/test_e1_rot_entropy_kat.py",
        "verify/cocotb/rot/Makefile.entropy_kat",
        "verify/cocotb/rot/e1_rot_keymgr_kat_tb.sv",
        "verify/cocotb/rot/test_e1_rot_keymgr_kat.py",
        "verify/cocotb/rot/Makefile.keymgr_kat",
        "external/opentitan/pin-manifest.json",
        "scripts/bootstrap_opentitan.sh",
    ]
    report = {
        "schema": "eliza.gate_status.v1",
        "gate": "rot-integration-check",
        "status": status,
        "blocker_id": blocker_id,
        "blocker_reason": blocker_reason,
        "evidence_paths": evidence_paths,
        "as_of": _now(),
        "subsystem": "security",
        **FALSE_CLAIM_FLAGS,
        "claim_boundary": (
            "The RoT INTEGRATION SPINE is real: the Ibex RV32IMC RoT core, the "
            "W4 OTP controller, the W5 lifecycle binding, the AP<->RoT TL-UL "
            "mailbox, and the fail-closed reset sequencer elaborate clean under "
            "Verilator and the reset-release + mailbox contracts pass in cocotb. " + boundary_crypto
        ),
        "block_inventory": {
            "real": real_blocks,
            "shimmed": shimmed,
            "real_count": len(real_blocks),
            "shimmed_count": len(shimmed),
        },
        "summary": {
            "check_count": len(checks),
            "passing_check_count": sum(1 for c in checks if c["status"] == "pass"),
            "failures": [c["id"] for c in checks if c["status"] != "pass"],
        },
        "checks": checks,
    }
    report["findings"] = structured_findings(
        checks=checks,
        shimmed=shimmed,
        blocker_id=blocker_id,
        blocker_reason=blocker_reason,
        evidence_paths=evidence_paths,
    )
    REPORT.write_text(json.dumps(report, indent=2) + "\n")

    print(f"STATUS: {status} rot-integration-check -> {REPORT.relative_to(ROOT)}")
    for c in checks:
        print(f"  [{c['status'].upper():7}] {c['id']}: {c['detail']}")
    print(f"  real blocks   ({len(real_blocks)}): {', '.join(real_blocks)}")
    print(f"  shimmed blocks({len(shimmed)}): {', '.join(s['block'] for s in shimmed)}")
    if blocker_reason:
        print(f"  blocker: {blocker_reason}")

    # Exit code: PASS -> 0; BLOCKED -> 2 (fail-closed, non-zero); FAIL -> 1.
    return {"PASS": 0, "BLOCKED": 2, "FAIL": 1}[status]


if __name__ == "__main__":
    sys.exit(main())
