#!/usr/bin/env python3
"""Generate a Verilator-elaborable filelist for an OpenTitan IP block.

Self-contained CAPI2 (.core) dependency resolver for the vendored Earl Grey
checkout (external/opentitan/opentitan, pinned in pin-manifest.json). Replaces
the fusesoc + primgen toolchain for the narrow purpose of staging a single
crypto/security block (hmac, kmac, aes, ...) plus its prim/tlul package closure
into a `.f` filelist that `verilator --lint-only` can elaborate.

Why not fusesoc: the upstream Earl Grey .core files target lowRISC's pinned
fusesoc fork (python-requirements.txt: lowRISC/fusesoc@ot). The current
pip-published fusesoc (2.4.6) rejects the older CAPI2 dict-style `files:` and
the `datatype: parameter` fields, so it cannot resolve these cores. This module
parses the same .core YAML directly and reproduces the two primgen actions we
need (single-techlib abstract-prim wrappers + prim_pkg.sv), which is sufficient
because only the `generic` techlib is vendored in this checkout.

Output is reproducible from `source tools/env.sh` + the vendored checkout:
generated wrappers land under build/rot_ot/generated/, the filelist under
build/rot_ot/flists/<block>.f.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OT = ROOT / "external/opentitan/opentitan"
HW = OT / "hw"
GEN_DIR = ROOT / "build/rot_ot/generated"
FLIST_DIR = ROOT / "build/rot_ot/flists"

# prim_name -> generated abstract wrapper module name prim_<prim_name>. Only the
# generic techlib is vendored, so each wrapper is a 1-techlib passthrough to
# prim_generic_<prim_name>.
PRIMGEN_ENUMS = ["ImplGeneric"]


# FuseSoC fileset flags. Standalone-IP elaboration uses the `fileset_ip`
# variant of each generated reg block (the in-tree rtl/*_reg_pkg.sv committed in
# this release), NOT the topgen `fileset_top`/`fileset_topgen` variants (which
# pull in the full top_earlgrey topgen-generated package chain).
ACTIVE_FLAGS = {"fileset_ip"}


def _vlnv_key(name: str) -> str:
    """vendor:library:name (drop the :version suffix) for version-agnostic deps."""
    parts = name.split(":")
    return ":".join(parts[:3])


def _expand_conditional(items):
    """Expand FuseSoC `<flag> ? (a b c)` and bare entries in a depend/files list.

    Returns the list of selected raw tokens. A conditional group is kept only
    when its flag is in ACTIVE_FLAGS; bare (unconditional) entries always pass.
    """
    out: list[str] = []
    for raw in items or []:
        if not isinstance(raw, str):
            out.append(raw)
            continue
        s = raw.strip()
        m = re.match(r"^(?P<flag>[\w]+)\s*\?\s*\((?P<body>.*)\)\s*$", s)
        if m:
            if m.group("flag") in ACTIVE_FLAGS:
                out.extend(tok for tok in m.group("body").split() if tok)
            continue
        out.append(s)
    return out


def _load_cores() -> dict[str, tuple[Path, dict]]:
    """Index every .core under hw/ by its version-agnostic VLNV key."""
    cores: dict[str, tuple[Path, dict]] = {}
    for core_path in HW.rglob("*.core"):
        text = core_path.read_text(encoding="utf-8", errors="replace")
        if not text.startswith("CAPI=2:"):
            continue
        try:
            data = yaml.safe_load(text)
        except yaml.YAMLError:
            continue
        if not isinstance(data, dict) or "name" not in data:
            continue
        key = _vlnv_key(data["name"])
        # First definition wins; Earl Grey has a few top-level duplicates we
        # never traverse into for a single-block closure.
        cores.setdefault(key, (core_path, data))
    return cores


def _iter_fileset_files(fileset: dict):
    """Yield (relpath, is_include) for each selected file entry in a fileset."""
    for entry in fileset.get("files", []) or []:
        if isinstance(entry, dict):
            for rel, attrs in entry.items():
                inc = bool(isinstance(attrs, dict) and attrs.get("is_include_file"))
                yield rel, inc
            continue
        if not isinstance(entry, str):
            continue
        for rel in _expand_conditional([entry]):
            yield rel, False


def _primgen_prim_name(data: dict) -> str | None:
    """If this core is an abstract prim generated by primgen, return prim_name."""
    gen = data.get("generate", {}) or {}
    for spec in gen.values():
        if not isinstance(spec, dict):
            continue
        if spec.get("generator") == "primgen":
            params = spec.get("parameters", {}) or {}
            if params.get("action") == "generate_prim_pkg":
                return "__prim_pkg__"
            if "prim_name" in params:
                return params["prim_name"]
    return None


_RE_MODULE = re.compile(
    r"(?:\s|^)module\s+(?:(?:static|automatic)\s+)?{name}"
    r"\s*(?P<imports>(?:import\s+[^;]+;)+)?"
    r"\s*(?:#\s*\((?P<params>.*?)\))?"
    r"\s*\(\s*(?P<ports>.*?)\s*\)\s*;",
    re.DOTALL,
)


def _parse_generic_header(generic_sv: Path, generic_module: str) -> dict:
    text = generic_sv.read_text(encoding="utf-8", errors="replace")
    m = re.compile(_RE_MODULE.pattern.format(name=generic_module), re.DOTALL).search(text)
    if not m:
        raise ValueError(f"cannot parse module header of {generic_module} in {generic_sv}")
    return {
        "imports": (m.group("imports") or "").strip(),
        "params": (m.group("params") or "").strip(),
        "ports": (m.group("ports") or "").strip(),
    }


def _gen_prim_pkg() -> Path:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    out = GEN_DIR / "prim_pkg.sv"
    enums = ",\n    ".join(PRIMGEN_ENUMS)
    out.write_text(
        "// AUTO-GENERATED by scripts/gen_ot_flist.py (primgen generate_prim_pkg "
        "equivalent).\n"
        "package prim_pkg;\n"
        "  typedef enum integer {\n"
        f"    {enums}\n"
        "  } impl_e;\n"
        "endpackage : prim_pkg\n"
    )
    return out


def _gen_abstract_prim(prim_name: str, cores: dict[str, tuple[Path, dict]]) -> Path:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    generic_module = f"prim_generic_{prim_name}"
    generic_sv = HW / "ip/prim_generic/rtl" / f"{generic_module}.sv"
    if not generic_sv.is_file():
        raise FileNotFoundError(f"missing generic impl {generic_sv}")
    hdr = _parse_generic_header(generic_sv, generic_module)
    params = f"#(\n{hdr['params']}\n) " if hdr["params"] else ""
    imports = f"\n{hdr['imports']}\n" if hdr["imports"] else "\n"
    body = (
        "// AUTO-GENERATED by scripts/gen_ot_flist.py (primgen single-techlib "
        f"wrapper for prim_{prim_name}).\n"
        f"module prim_{prim_name}{imports}{params}(\n  {hdr['ports']}\n);\n"
        "  if (1) begin : gen_generic\n"
        f"    {generic_module}"
    )
    if hdr["params"]:
        plist = _param_names(hdr["params"])
        body += " #(\n" + ",\n".join(f"      .{p}({p})" for p in plist) + "\n    )"
    body += " u_impl_generic (\n      .*\n    );\n  end\nendmodule\n"
    out = GEN_DIR / f"prim_{prim_name}.sv"
    out.write_text(body)
    return out


_RE_PARAM = re.compile(
    r"parameter\s+(?:[a-zA-Z0-9_\]\[:\s$\.-]+\s+)?(?P<name>\w+)(?:\s*=\s*[^,;]+)?"
)


def _param_names(param_list: str) -> list[str]:
    names: list[str] = []
    for m in _RE_PARAM.finditer(param_list):
        if m.group("name") not in names:
            names.append(m.group("name"))
    return names


def resolve(block_vlnv: str, cores: dict[str, tuple[Path, dict]]):
    """Topologically resolve a block's RTL closure.

    Returns (ordered_sources, incdirs, generated_first). Generated prim_pkg /
    abstract-prim wrappers are emitted into GEN_DIR and slotted ahead of the
    cores that depend on them.
    """
    order: list[Path] = []
    incdirs: list[Path] = []
    seen: set[str] = set()
    generated: dict[str, Path] = {}

    def visit(key: str):
        if key in seen:
            return
        seen.add(key)
        if key not in cores:
            raise KeyError(f"unresolved core dependency: {key}")
        core_path, data = cores[key]
        prim_name = _primgen_prim_name(data)
        # Visit dependencies first (post-order => deps emitted before dependents).
        for fs in (data.get("filesets") or {}).values():
            if not isinstance(fs, dict):
                continue
            for dep in _expand_conditional(fs.get("depend", [])):
                dep_key = _vlnv_key(dep)
                # Skip lint/tool waiver cores; they carry no RTL we elaborate.
                if dep_key.startswith("lowrisc:lint"):
                    continue
                visit(dep_key)
        # Emit primgen artifacts for abstract cores.
        if prim_name == "__prim_pkg__":
            if "prim_pkg" not in generated:
                generated["prim_pkg"] = _gen_prim_pkg()
                order.append(generated["prim_pkg"])
            return
        if prim_name and prim_name != "__prim_pkg__":
            gkey = f"prim_{prim_name}"
            if gkey not in generated:
                generated[gkey] = _gen_abstract_prim(prim_name, cores)
            # The abstract core only depends on the primgen *generator*; the
            # real generic implementation lives in lowrisc:prim_generic:<name>.
            # primgen synthesizes that techlib dependency, so we add it here so
            # the prim_generic_<name>.sv files land ahead of the wrapper.
            visit(f"lowrisc:prim_generic:{prim_name}")
        core_root = core_path.parent
        for fs in (data.get("filesets") or {}).values():
            # Only RTL filesets carry sources we elaborate; skip vlt/waiver etc.
            if not isinstance(fs, dict):
                continue
            if fs.get("file_type") not in (None, "systemVerilogSource"):
                continue
            for rel, is_inc in _iter_fileset_files(fs):
                fpath = (core_root / rel).resolve()
                if not fpath.is_file():
                    continue
                # .svh and is_include_file entries are header includes (+incdir);
                # only .sv entries are compiled, in dependency order.
                if is_inc or fpath.suffix == ".svh":
                    if fpath.parent not in incdirs:
                        incdirs.append(fpath.parent)
                elif fpath.suffix == ".sv" and fpath not in order:
                    order.append(fpath)
        if prim_name and prim_name != "__prim_pkg__":
            order.append(generated[f"prim_{prim_name}"])

    visit(_vlnv_key(block_vlnv))
    return order, incdirs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("block_vlnv", help="e.g. lowrisc:ip:hmac")
    ap.add_argument("--out", help="output .f path (default build/rot_ot/flists/<name>.f)")
    args = ap.parse_args()

    cores = _load_cores()
    order, incdirs = resolve(args.block_vlnv, cores)

    FLIST_DIR.mkdir(parents=True, exist_ok=True)
    name = args.block_vlnv.split(":")[2]
    out = Path(args.out) if args.out else FLIST_DIR / f"{name}.f"
    lines = [f"+incdir+{d}" for d in incdirs] + [str(p) for p in order]
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}: {len(order)} sources, {len(incdirs)} incdirs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
