#!/usr/bin/env python3
"""Generate platform artifacts from the e1 platform contract.

This script is the single emission point for the Linux-capable CPU SoC variant
of the e1 chip. It reads sw/platform/e1_platform_contract.json
("e1_chip_cpu_variant" section) and writes:

  (a) sw/platform/generated/e1_platform.vh
        Verilog header with address constants for RTL decode.
  (b) sw/platform/generated/e1-platform.dtsi
        Device tree source include for the kernel.
  (c) sw/platform/generated/e1_platform.h
        C header for U-Boot, OpenSBI, and bare-metal firmware.
  (d) sw/platform/generated/e1_platform_hal.json
        AOSP HAL configuration JSON.

The companion check script scripts/check_platform_contract.py invokes the
same generator functions to detect divergence in CI.

Usage:
  scripts/gen_platform_artifacts.py            # write all artifacts
  scripts/gen_platform_artifacts.py --check    # exit non-zero if stale
  scripts/gen_platform_artifacts.py --stdout vh|dtsi|h|hal
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "sw/platform/e1_platform_contract.json"
OUT_DIR = ROOT / "sw/platform/generated"

ARTIFACTS = {
    "vh": "e1_platform.vh",
    "dtsi": "e1-platform.dtsi",
    "h": "e1_platform.h",
    "hal": "e1_platform_hal.json",
}

HEADER_COMMENT = (
    "Generated by scripts/gen_platform_artifacts.py from "
    "sw/platform/e1_platform_contract.json. DO NOT EDIT BY HAND."
)


def _h(value) -> int:
    if isinstance(value, int):
        return value
    return int(str(value).replace("_", ""), 0)


def _hex(value, width: int = 8) -> str:
    return f"0x{_h(value):0{width}X}"


def load_contract() -> dict:
    return json.loads(CONTRACT_PATH.read_text())


def cpu_variant(contract: dict) -> dict:
    if "e1_chip_cpu_variant" not in contract:
        raise SystemExit(
            "contract is missing e1_chip_cpu_variant; extend sw/platform/e1_platform_contract.json"
        )
    return contract["e1_chip_cpu_variant"]


def e1_chip_regions(contract: dict) -> dict[str, dict]:
    return {region["name"]: region for region in contract["e1_chip"]["regions"]}


# ---------------------------------------------------------------------------
# (a) Verilog header
# ---------------------------------------------------------------------------
def gen_verilog_header(contract: dict) -> str:
    v = cpu_variant(contract)
    lines = [
        f"// {HEADER_COMMENT}",
        "`ifndef E1_PLATFORM_VH",
        "`define E1_PLATFORM_VH",
        "",
        f"`define E1_RESET_VECTOR 32'h{_h(v['boot']['reset_vector']):08X}",
        f"`define E1_ROM_BASE     32'h{_h(v['boot']['rom_base']):08X}",
        f"`define E1_ROM_SIZE     32'h{_h(v['boot']['rom_size']):08X}",
        f"`define E1_DRAM_BASE    32'h{_h(v['dram']['base']):08X}",
        f"`define E1_DRAM_SIZE    32'h{_h(v['dram']['size']):08X}",
        f"`define E1_PLIC_BASE    32'h{_h(v['plic']['base']):08X}",
        f"`define E1_PLIC_SIZE    32'h{_h(v['plic']['size']):08X}",
        f"`define E1_CLINT_BASE   32'h{_h(v['clint']['base']):08X}",
        f"`define E1_CLINT_SIZE   32'h{_h(v['clint']['size']):08X}",
        f"`define E1_UART_BASE    32'h{_h(v['uart']['base']):08X}",
        f"`define E1_UART_SIZE    32'h{_h(v['uart']['size']):08X}",
        "",
    ]
    for name, dev in v["devices"].items():
        lines.append(f"`define E1_{name.upper()}_BASE    32'h{_h(dev['base']):08X}")
        lines.append(f"`define E1_{name.upper()}_SIZE    32'h{_h(dev['size']):08X}")
    lines.append("")
    for irq_name, irq_id in v["interrupts"].items():
        lines.append(f"`define E1_{irq_name} {int(irq_id)}")
    lines += ["", "`endif // E1_PLATFORM_VH", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# (b) DTS include
# ---------------------------------------------------------------------------
def gen_dtsi(contract: dict) -> str:
    v = cpu_variant(contract)
    plic = v["plic"]
    clint = v["clint"]
    uart = v["uart"]
    irqs = v["interrupts"]
    devs = v["devices"]

    def reg(base, size):
        return f"<0x0 {_hex(base)} 0x0 {_hex(size)}>"

    lines = [
        "// SPDX-License-Identifier: GPL-2.0-only OR BSD-2-Clause",
        f"// {HEADER_COMMENT}",
        "/ {",
        "\t#address-cells = <2>;",
        "\t#size-cells = <2>;",
        "",
        "\tcpus {",
        "\t\t#address-cells = <1>;",
        "\t\t#size-cells = <0>;",
        f"\t\ttimebase-frequency = <{int(v['timebase_frequency_hz'])}>;",
        "\t\tcpu@0 {",
        '\t\t\tdevice_type = "cpu";',
        "\t\t\treg = <0>;",
        '\t\t\tstatus = "okay";',
        '\t\t\tcompatible = "riscv";',
        f'\t\t\triscv,isa = "{v["isa"]}";',
        '\t\t\tmmu-type = "riscv,sv39";',
        "\t\t\tcpu0_intc: interrupt-controller {",
        "\t\t\t\t#interrupt-cells = <1>;",
        "\t\t\t\tinterrupt-controller;",
        '\t\t\t\tcompatible = "riscv,cpu-intc";',
        "\t\t\t};",
        "\t\t};",
        "\t};",
        "",
        "\tmemory@" + f"{_h(v['dram']['base']):x}" + " {",
        '\t\tdevice_type = "memory";',
        f"\t\treg = {reg(v['dram']['base'], v['dram']['size'])};",
        "\t};",
        "",
        "\tsoc {",
        '\t\tcompatible = "simple-bus";',
        "\t\t#address-cells = <2>;",
        "\t\t#size-cells = <2>;",
        "\t\tranges;",
        "",
        f"\t\tclint@{_h(clint['base']):x} {{",
        '\t\t\tcompatible = "sifive,clint0", "riscv,clint0";',
        f"\t\t\treg = {reg(clint['base'], clint['size'])};",
        f"\t\t\tinterrupts-extended = <&cpu0_intc 3>, <&cpu0_intc {int(irqs['IRQ_TIMER'])}>;",
        "\t\t};",
        "",
        f"\t\tplic: plic@{_h(plic['base']):x} {{",
        '\t\t\tcompatible = "sifive,plic-1.0.0", "riscv,plic0";',
        f"\t\t\treg = {reg(plic['base'], plic['size'])};",
        "\t\t\t#interrupt-cells = <1>;",
        "\t\t\tinterrupt-controller;",
        "\t\t\tinterrupts-extended = <&cpu0_intc 11>, <&cpu0_intc 9>;",
        f"\t\t\triscv,ndev = <{int(plic['num_sources'])}>;",
        "\t\t};",
        "",
        f"\t\tuart0: serial@{_h(uart['base']):x} {{",
        f'\t\t\tcompatible = "{uart["compatible"]}";',
        f"\t\t\treg = {reg(uart['base'], uart['size'])};",
        f"\t\t\tclock-frequency = <{int(uart['clock_frequency_hz'])}>;",
        f"\t\t\tcurrent-speed = <{int(uart['baud'])}>;",
        f"\t\t\treg-shift = <{int(uart.get('reg_shift', 0))}>;",
        "\t\t\tinterrupt-parent = <&plic>;",
        f"\t\t\tinterrupts = <{int(uart['irq'])}>;",
        "\t\t};",
        "",
    ]
    for name, dev in devs.items():
        node = f"e1_{name}"
        lines += [
            f"\t\t{node}: {name}@{_h(dev['base']):x} {{",
            f'\t\t\tcompatible = "{dev["compatible"]}";',
            f"\t\t\treg = {reg(dev['base'], dev['size'])};",
            "\t\t\tinterrupt-parent = <&plic>;",
            f"\t\t\tinterrupts = <{int(dev['irq'])}>;",
            "\t\t};",
            "",
        ]
    lines += ["\t};", "};", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# (c) C header
# ---------------------------------------------------------------------------
def gen_c_header(contract: dict) -> str:
    v = cpu_variant(contract)
    regions = e1_chip_regions(contract)
    lines = [
        f"/* {HEADER_COMMENT} */",
        "#ifndef E1_PLATFORM_H",
        "#define E1_PLATFORM_H",
        "",
        f"#define E1_RESET_VECTOR  {_hex(v['boot']['reset_vector'])}UL",
        f"#define E1_ROM_BASE      {_hex(v['boot']['rom_base'])}UL",
        f"#define E1_ROM_SIZE      {_hex(v['boot']['rom_size'])}UL",
        f"#define E1_SBI_ENTRY     {_hex(v['boot']['sbi_entry'])}UL",
        f"#define E1_KERNEL_ENTRY  {_hex(v['boot']['kernel_entry'])}UL",
        "",
        f"#define E1_DRAM_BASE     {_hex(v['dram']['base'])}UL",
        f"#define E1_DRAM_SIZE     {_hex(v['dram']['size'])}UL",
        "",
        f"#define E1_PLIC_BASE     {_hex(v['plic']['base'])}UL",
        f"#define E1_PLIC_SIZE     {_hex(v['plic']['size'])}UL",
        f"#define E1_PLIC_NSOURCES {int(v['plic']['num_sources'])}",
        "",
        f"#define E1_CLINT_BASE    {_hex(v['clint']['base'])}UL",
        f"#define E1_CLINT_SIZE    {_hex(v['clint']['size'])}UL",
        "",
        f"#define E1_UART_BASE     {_hex(v['uart']['base'])}UL",
        f"#define E1_UART_SIZE     {_hex(v['uart']['size'])}UL",
        f"#define E1_UART_CLK_HZ   {int(v['uart']['clock_frequency_hz'])}U",
        f"#define E1_UART_BAUD     {int(v['uart']['baud'])}U",
        f"#define E1_TIMEBASE_HZ   {int(v['timebase_frequency_hz'])}U",
        "",
    ]
    for name, dev in v["devices"].items():
        u = name.upper()
        lines.append(f"#define E1_{u}_BASE     {_hex(dev['base'])}UL")
        lines.append(f"#define E1_{u}_SIZE     {_hex(dev['size'])}UL")
        region = regions.get(name)
        if region and "registers" in region:
            for reg in region["registers"]:
                lines.append(f"#define E1_{u}_{reg['name']}_OFFSET {_hex(reg['offset'], 2)}UL")
    lines.append("")
    for irq_name, irq_id in v["interrupts"].items():
        lines.append(f"#define E1_{irq_name} {int(irq_id)}")
    lines += ["", "#endif /* E1_PLATFORM_H */", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# (d) AOSP HAL JSON
# ---------------------------------------------------------------------------
def gen_hal_json(contract: dict) -> str:
    v = cpu_variant(contract)
    regions = e1_chip_regions(contract)
    data = {
        "_generated_from": "sw/platform/e1_platform_contract.json",
        "_generator": "scripts/gen_platform_artifacts.py",
        "platform": "eliza-e1-cpu-variant",
        "isa": v["isa"],
        "memory": {
            "dram_base": _hex(v["dram"]["base"]),
            "dram_size": _hex(v["dram"]["size"]),
        },
        "uart": {
            "base": _hex(v["uart"]["base"]),
            "size": _hex(v["uart"]["size"]),
            "irq": int(v["uart"]["irq"]),
            "baud": int(v["uart"]["baud"]),
        },
        "interrupts": {k: int(val) for k, val in v["interrupts"].items()},
        "devices": {
            name: {
                "base": _hex(dev["base"]),
                "size": _hex(dev["size"]),
                "irq": int(dev["irq"]),
                "compatible": dev["compatible"],
                "registers": {
                    reg["name"]: _hex(reg["offset"], 2)
                    for reg in regions.get(name, {}).get("registers", [])
                },
            }
            for name, dev in v["devices"].items()
        },
    }
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


GENERATORS = {
    "vh": gen_verilog_header,
    "dtsi": gen_dtsi,
    "h": gen_c_header,
    "hal": gen_hal_json,
}


def generate_all(contract: dict) -> dict[str, str]:
    return {kind: GENERATORS[kind](contract) for kind in ARTIFACTS}


def write_all(contents: dict[str, str]) -> list[Path]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for kind, name in ARTIFACTS.items():
        path = OUT_DIR / name
        path.write_text(contents[kind])
        written.append(path)
    return written


def check_all(contents: dict[str, str]) -> list[str]:
    errors = []
    for kind, name in ARTIFACTS.items():
        path = OUT_DIR / name
        if not path.is_file():
            errors.append(f"{path.relative_to(ROOT)} is missing; run `make platform-artifacts`")
            continue
        actual = path.read_text()
        if actual != contents[kind]:
            errors.append(
                f"{path.relative_to(ROOT)} is stale; regenerate with `make platform-artifacts`"
            )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if any generated artifact is stale"
    )
    parser.add_argument(
        "--stdout", choices=sorted(ARTIFACTS), help="emit one artifact to stdout instead of writing"
    )
    args = parser.parse_args()

    contract = load_contract()
    contents = generate_all(contract)

    if args.stdout:
        sys.stdout.write(contents[args.stdout])
        return 0

    if args.check:
        errors = check_all(contents)
        if errors:
            print("Platform artifact check failed:")
            for e in errors:
                print(f"  - {e}")
            return 1
        print("Platform artifacts are up to date.")
        return 0

    written = write_all(contents)
    for path in written:
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
