#!/usr/bin/env python3
"""Validate CUDA-capable PyTorch macro-placement training artifacts.

The checker intentionally does not import torch. It validates the JSON report,
dataset linkage, metric ranges, and that the serialized model file exists and
has nonzero size. CUDA/MPS/CPU execution is captured in the report generated by
train_macro_placement_torch_regressor.py.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_REPORT = (
    ROOT / "build/ai_eda/macro_placement_torch_regressor/validation/torch_training_run.json"
)
TRAINING_CLAIM_BOUNDARY = (
    "macro_placement_torch_regressor_training_only_no_inference_replay_or_release_claim"
)
REQUIRED_SPLITS = ("train", "val", "test")


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def repo_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else ROOT / path


def load_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: expected JSON object")
    return data


def jsonl_count(path: Path) -> int:
    with path.open("r", encoding="utf-8") as handle:
        return sum(1 for line in handle if line.strip())


def valid_metric(value: Any, upper: float = 2.0) -> bool:
    return (
        isinstance(value, (int, float))
        and math.isfinite(float(value))
        and 0.0 <= float(value) <= upper
    )


def validate_metrics(
    metrics: dict[str, Any], dataset_dir: Path, report: dict[str, Any]
) -> list[str]:
    errors: list[str] = []
    if metrics.get("schema") != "eliza.ai_eda.macro_placement_torch_regressor_metrics.v1":
        errors.append(
            "metrics schema must be eliza.ai_eda.macro_placement_torch_regressor_metrics.v1"
        )
    if metrics.get("claim_boundary") != TRAINING_CLAIM_BOUNDARY:
        errors.append("metrics claim_boundary is missing or incorrect")
    if metrics.get("release_use_allowed") is not False:
        errors.append("metrics release_use_allowed must be false")
    if metrics.get("device") != report.get("device"):
        errors.append("metrics device does not match report device")
    if not isinstance(metrics.get("epochs"), int) or int(metrics["epochs"]) <= 0:
        errors.append("metrics epochs must be a positive integer")
    elif report.get("epochs") != metrics.get("epochs"):
        errors.append("metrics epochs does not match report epochs")

    splits = metrics.get("splits")
    if not isinstance(splits, list):
        errors.append("metrics.splits must be a list")
        return errors
    by_split = {item.get("split"): item for item in splits if isinstance(item, dict)}
    for split in REQUIRED_SPLITS:
        item = by_split.get(split)
        if not isinstance(item, dict):
            errors.append(f"metrics missing split {split}")
            continue
        split_file = dataset_dir / f"{split}.jsonl"
        if not split_file.exists():
            errors.append(f"missing dataset split file {rel(split_file)}")
            continue
        expected_count = jsonl_count(split_file)
        if item.get("sample_count") != expected_count:
            errors.append(f"{split}: sample_count does not match dataset split file")
        for field in ("mae_x_over_core", "mae_y_over_core", "mean_l1_over_core"):
            if not valid_metric(item.get(field)):
                errors.append(f"{split}: invalid {field}")
        if not valid_metric(item.get("orientation_accuracy"), upper=1.0):
            errors.append(f"{split}: invalid orientation_accuracy")

    history = metrics.get("loss_history")
    if not isinstance(history, list) or not history:
        errors.append("metrics.loss_history must be a non-empty list")
    else:
        previous_epoch = 0
        for item in history:
            if not isinstance(item, dict):
                errors.append("metrics.loss_history entries must be objects")
                continue
            epoch = item.get("epoch")
            if not isinstance(epoch, int) or epoch <= previous_epoch:
                errors.append("metrics.loss_history epochs must be strictly increasing")
            previous_epoch = int(epoch) if isinstance(epoch, int) else previous_epoch
            if not valid_metric(item.get("loss"), upper=1000.0):
                errors.append(
                    "metrics.loss_history loss values must be finite non-negative numbers"
                )
    return errors


def validate_report(report: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if report.get("schema") != "eliza.ai_eda.macro_placement_torch_regressor_training_run.v1":
        errors.append(
            "report schema must be eliza.ai_eda.macro_placement_torch_regressor_training_run.v1"
        )
    if report.get("claim_boundary") != TRAINING_CLAIM_BOUNDARY:
        errors.append("report claim_boundary is missing or incorrect")
    if report.get("release_use_allowed") is not False:
        errors.append("report release_use_allowed must be false")
    if report.get("device") not in {"cpu", "cuda", "mps"}:
        errors.append("report device must be cpu, cuda, or mps")
    if not isinstance(report.get("epochs"), int) or int(report["epochs"]) <= 0:
        errors.append("report epochs must be a positive integer")

    dataset_dir = repo_path(str(report.get("dataset_dir", "")))
    model_path = repo_path(str(report.get("model", "")))
    metrics_path = repo_path(str(report.get("metrics", "")))
    for label, path in (
        ("dataset_dir", dataset_dir),
        ("model", model_path),
        ("metrics", metrics_path),
    ):
        if not path.exists():
            errors.append(f"missing {label}: {rel(path)}")
    if errors:
        return errors
    if not dataset_dir.is_dir():
        errors.append(f"dataset_dir is not a directory: {rel(dataset_dir)}")
    if model_path.stat().st_size <= 0:
        errors.append(f"model file is empty: {rel(model_path)}")

    count_fields = {
        "train": "train_sample_count",
        "val": "val_sample_count",
        "test": "test_sample_count",
    }
    for split, field in count_fields.items():
        split_file = dataset_dir / f"{split}.jsonl"
        if not split_file.exists():
            errors.append(f"missing dataset split file {rel(split_file)}")
            continue
        if report.get(field) != jsonl_count(split_file):
            errors.append(f"report {field} does not match {split}.jsonl")

    try:
        metrics = load_json(metrics_path)
    except Exception as exc:  # noqa: BLE001
        errors.append(f"failed to load metrics: {exc}")
    else:
        errors.extend(validate_metrics(metrics, dataset_dir, report))
    return errors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.report.exists():
        print(f"STATUS: FAIL ai_eda.macro_placement_torch_regressor missing_report {args.report}")
        return 1
    try:
        report = load_json(args.report)
    except Exception as exc:  # noqa: BLE001
        print(f"STATUS: FAIL ai_eda.macro_placement_torch_regressor {args.report}: {exc}")
        return 1
    errors = validate_report(report)
    if errors:
        for error in errors:
            print(f"STATUS: FAIL ai_eda.macro_placement_torch_regressor {error}")
        return 1
    print(
        "STATUS: PASS ai_eda.macro_placement_torch_regressor "
        f"device={report['device']} train={report['train_sample_count']} "
        f"val={report['val_sample_count']} test={report['test_sample_count']} "
        f"claim_boundary={TRAINING_CLAIM_BOUNDARY}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
