import {
  DESKTOP_WORKSPACE_SURFACES,
  type DesktopClickAuditItem,
} from "../../utils/desktop-workspace";

export const DESKTOP_WORKSPACE_CLICK_AUDIT: readonly DesktopClickAuditItem[] = [
  {
    id: "desktop-refresh-snapshot",
    entryPoint: "settings:desktop",
    label: "Refresh Diagnostics",
    expectedAction:
      "Reload desktop version, window, display, clipboard, and path diagnostics.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-open-settings-window",
    entryPoint: "settings:desktop",
    label: "Open Desktop Settings Window",
    expectedAction:
      "Open a detached settings window focused on the desktop section.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-show-window",
    entryPoint: "settings:desktop",
    label: "Show Window",
    expectedAction: "Show the main desktop window.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-hide-window",
    entryPoint: "settings:desktop",
    label: "Hide Window",
    expectedAction: "Hide the main desktop window.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-focus-window",
    entryPoint: "settings:desktop",
    label: "Focus Window",
    expectedAction: "Focus the main desktop window.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-minimize-window",
    entryPoint: "settings:desktop",
    label: "Minimize Window",
    expectedAction: "Minimize the main desktop window.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-maximize-toggle",
    entryPoint: "settings:desktop",
    label: "Toggle Maximize",
    expectedAction: "Maximize or unmaximize the main desktop window.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-notify",
    entryPoint: "settings:desktop",
    label: "Send Test Notification",
    expectedAction: "Send a desktop notification.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-restart-agent",
    entryPoint: "settings:desktop",
    label: "Restart Agent",
    expectedAction: "Restart the desktop agent backend.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-relaunch-app",
    entryPoint: "settings:desktop",
    label: "Relaunch app",
    expectedAction: "Relaunch the desktop shell.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-toggle-auto-launch",
    entryPoint: "settings:desktop",
    label: "Toggle Auto-launch",
    expectedAction: "Enable or disable auto-launch.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-toggle-hidden-launch",
    entryPoint: "settings:desktop",
    label: "Toggle Hidden Start",
    expectedAction:
      "Toggle launching the app hidden when auto-launch is enabled.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-open-file-dialog",
    entryPoint: "settings:desktop",
    label: "Open Files Dialog",
    expectedAction: "Open a native file chooser.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-open-folder-dialog",
    entryPoint: "settings:desktop",
    label: "Open Folder Dialog",
    expectedAction: "Open a native directory chooser.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-save-dialog",
    entryPoint: "settings:desktop",
    label: "Save File Dialog",
    expectedAction: "Open a native save dialog.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-clipboard-read",
    entryPoint: "settings:desktop",
    label: "Read Clipboard",
    expectedAction:
      "Read text, html, rtf, and format metadata from the system clipboard.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-clipboard-copy",
    entryPoint: "settings:desktop",
    label: "Copy Clipboard Draft",
    expectedAction: "Write text to the system clipboard.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-clipboard-clear",
    entryPoint: "settings:desktop",
    label: "Clear Clipboard",
    expectedAction: "Clear the system clipboard.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-open-path",
    entryPoint: "settings:desktop",
    label: "Open Desktop Path",
    expectedAction: "Open a selected filesystem path using the native shell.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  {
    id: "desktop-reveal-path",
    entryPoint: "settings:desktop",
    label: "Reveal Desktop Path",
    expectedAction:
      "Reveal a selected filesystem path in the native file manager.",
    runtimeRequirement: "desktop",
    coverage: "automated",
  },
  ...DESKTOP_WORKSPACE_SURFACES.map(
    (surface): DesktopClickAuditItem => ({
      id: `desktop-surface-${surface.id}`,
      entryPoint: "settings:desktop",
      label: surface.label,
      expectedAction: `Open the detached ${surface.id} surface window.`,
      runtimeRequirement: "desktop",
      coverage: "automated",
    }),
  ),
] as const;
