"""Generate ``profiles/erobot/profile.yaml`` from the spec.

The emitted manifest validates against the canonical
:class:`eliza_robot.profiles.schema.RobotProfile` (``extra="forbid"``), so
every code path that resolves a robot via ``load_profile("erobot")`` works
unchanged. Joints, torque/velocity limits, contact geoms, and the stand pose
are all derived from the spec — never hand-typed.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from eliza_robot.erobot.mjcf import _spawn_height
from eliza_robot.erobot.spec import RobotSpec, build_spec

PROFILES_ROOT = Path(__file__).resolve().parents[2] / "profiles" / "erobot"


def build_profile_dict(spec: RobotSpec | None = None) -> dict[str, Any]:
    spec = spec or build_spec()
    default_height = round(_spawn_height(spec), 4)

    joints = [
        {
            "name": j.name,
            "index": j.index,
            "lower_rad": round(j.lower_rad, 6),
            "upper_rad": round(j.upper_rad, 6),
            "home_rad": round(j.home_rad, 6),
            "group": j.group,
            "actuator_torque_nm": j.torque_nm,
            "velocity_max_rad_s": j.velocity_max_rad_s,
        }
        for j in sorted(spec.joints, key=lambda j: j.index)
    ]

    stand_frame = {j.name: round(j.home_rad, 6) for j in sorted(spec.joints, key=lambda j: j.index)}

    return {
        "id": "erobot",
        "name": "erobot",
        "version": "1.0.0",
        "description": (
            "Full-size (~1.66 m, ~26 kg) 25-DoF humanoid designed from scratch. "
            "Hollow injection-molded shells (PA6-GF30 load paths, PC-ABS cosmetic, "
            "TPU soles) over off-the-shelf quasi-direct-drive actuators. Built and "
            "simulated entirely from the eliza_robot.erobot parametric spec."
        ),
        "kinematics": {"dof": spec.dof, "joints": joints},
        "gait": {
            "cycle_hz": 1.0,
            "swing_height_m": 0.06,
            "stance_width_m": round(2 * spec.dims.hip_half_width, 4),
            "step_length_max_m": 0.30,
            "foot_offset_m": -default_height,
            "default_height_m": default_height,
            "controller": "rl",
        },
        "contact": {
            "floor_geom_names": ["floor"],
            "left_foot_geom_names": ["left_foot_sole_col", "left_toe_sole_col"],
            "right_foot_geom_names": ["right_foot_sole_col", "right_toe_sole_col"],
        },
        "sensors": {
            "imu_noise_std": 0.005,
            "locomotion_tracking_body": "pelvis",
            "cameras": [
                {
                    "name": "chest_cam",
                    "width": 640,
                    "height": 480,
                    "fps": 30,
                    "fov_deg": 70.0,
                    "mount_link": "torso",
                    "extrinsics_rpy_xyz": [0.0, 0.0, 0.0, 0.09, 0.0, 0.38],
                }
            ],
        },
        "control": {
            "rate_hz": 50.0,
            "command_smoothing": 0.2,
            "max_joint_delta_rad_per_step": 0.15,
            "safe_torque_clip_nm": 120.0,
        },
        "assets": {
            "mjcf_xml": "mjcf/erobot.xml",
            "mjx_xml": "mjcf/erobot.xml",
            "urdf": "erobot.urdf",
            "mesh_dir": "mesh",
            "scene_xml": "mjcf/scene.xml",
        },
        "actions": {
            "groups": {
                "stand": {
                    "name": "stand",
                    "duration_s": 1.0,
                    "frames": [{"t": 0.0, "joints": stand_frame}],
                }
            }
        },
        "safety": {
            "fall_pitch_rad": 0.8,
            "fall_roll_rad": 0.8,
            "battery_low_mv": 39000,
            "deadman_timeout_s": 1.0,
        },
        "bridge_capabilities": [
            "policy.start",
            "policy.stop",
            "policy.tick",
            "policy.status",
            "action.play",
            "walk.command",
            "stand",
            "stop",
            "camera.snapshot",
            "profile.describe",
        ],
    }


def write_profile(spec: RobotSpec | None = None) -> Path:
    spec = spec or build_spec()
    PROFILES_ROOT.mkdir(parents=True, exist_ok=True)
    data = build_profile_dict(spec)
    out = PROFILES_ROOT / "profile.yaml"
    header = (
        "# Auto-generated by eliza_robot.erobot.profile from the parametric spec.\n"
        "# Do not hand-edit; re-run `python -m eliza_robot.erobot.build`.\n"
    )
    with out.open("w", encoding="utf-8") as fh:
        fh.write(header)
        yaml.safe_dump(data, fh, sort_keys=False, default_flow_style=False)
    return out


if __name__ == "__main__":
    out = write_profile()
    print(f"wrote {out}")
    from eliza_robot.profiles.schema import load_profile

    prof = load_profile("erobot")
    print(f"validated: {prof.id} — {prof.kinematics.dof} DoF, controller={prof.gait.controller}")
